"""
A 股 + 港股核心股票池
涵盖各行业龙头、高关注度标的，共 300+ 只
用于种子数据初始化和搜索扩展
"""

A_SHARE_STOCKS = [
    # ===== 白酒 =====
    {"symbol": "600519", "name": "贵州茅台", "industry": "白酒", "sector": "消费"},
    {"symbol": "000858", "name": "五粮液", "industry": "白酒", "sector": "消费"},
    {"symbol": "000568", "name": "泸州老窖", "industry": "白酒", "sector": "消费"},
    {"symbol": "002304", "name": "洋河股份", "industry": "白酒", "sector": "消费"},
    {"symbol": "600809", "name": "山西汾酒", "industry": "白酒", "sector": "消费"},
    {"symbol": "000596", "name": "古井贡酒", "industry": "白酒", "sector": "消费"},
    {"symbol": "603369", "name": "今世缘", "industry": "白酒", "sector": "消费"},
    {"symbol": "600779", "name": "水井坊", "industry": "白酒", "sector": "消费"},
    {"symbol": "000799", "name": "酒鬼酒", "industry": "白酒", "sector": "消费"},
    {"symbol": "603589", "name": "口子窖", "industry": "白酒", "sector": "消费"},

    # ===== 食品饮料 =====
    {"symbol": "600887", "name": "伊利股份", "industry": "乳制品", "sector": "消费"},
    {"symbol": "603288", "name": "海天味业", "industry": "调味品", "sector": "消费"},
    {"symbol": "600882", "name": "妙可蓝多", "industry": "乳制品", "sector": "消费"},
    {"symbol": "002557", "name": "洽洽食品", "industry": "休闲食品", "sector": "消费"},
    {"symbol": "603517", "name": "绝味食品", "industry": "卤制品", "sector": "消费"},
    {"symbol": "002507", "name": "涪陵榨菜", "industry": "调味品", "sector": "消费"},
    {"symbol": "603027", "name": "千禾味业", "industry": "调味品", "sector": "消费"},
    {"symbol": "600597", "name": "光明乳业", "industry": "乳制品", "sector": "消费"},
    {"symbol": "000895", "name": "双汇发展", "industry": "肉制品", "sector": "消费"},
    {"symbol": "600600", "name": "青岛啤酒", "industry": "啤酒", "sector": "消费"},
    {"symbol": "600132", "name": "重庆啤酒", "industry": "啤酒", "sector": "消费"},
    {"symbol": "002304", "name": "洋河股份", "industry": "白酒", "sector": "消费"},

    # ===== 家电 =====
    {"symbol": "000651", "name": "格力电器", "industry": "空调", "sector": "消费"},
    {"symbol": "000333", "name": "美的集团", "industry": "家电", "sector": "消费"},
    {"symbol": "002032", "name": "苏泊尔", "industry": "小家电", "sector": "消费"},
    {"symbol": "002508", "name": "老板电器", "industry": "厨电", "sector": "消费"},
    {"symbol": "603486", "name": "科沃斯", "industry": "扫地机器人", "sector": "消费"},
    {"symbol": "002242", "name": "九阳股份", "industry": "小家电", "sector": "消费"},
    {"symbol": "600060", "name": "海信视像", "industry": "黑电", "sector": "消费"},

    # ===== 纺织服饰 =====
    {"symbol": "600398", "name": "海澜之家", "industry": "男装", "sector": "消费"},
    {"symbol": "002563", "name": "森马服饰", "industry": "休闲服饰", "sector": "消费"},
    {"symbol": "603877", "name": "太平鸟", "industry": "时尚服饰", "sector": "消费"},

    # ===== 银行 =====
    {"symbol": "600036", "name": "招商银行", "industry": "银行", "sector": "金融"},
    {"symbol": "000001", "name": "平安银行", "industry": "银行", "sector": "金融"},
    {"symbol": "601166", "name": "兴业银行", "industry": "银行", "sector": "金融"},
    {"symbol": "601398", "name": "工商银行", "industry": "银行", "sector": "金融"},
    {"symbol": "601939", "name": "建设银行", "industry": "银行", "sector": "金融"},
    {"symbol": "601288", "name": "农业银行", "industry": "银行", "sector": "金融"},
    {"symbol": "601988", "name": "中国银行", "industry": "银行", "sector": "金融"},
    {"symbol": "600000", "name": "浦发银行", "industry": "银行", "sector": "金融"},
    {"symbol": "600016", "name": "民生银行", "industry": "银行", "sector": "金融"},
    {"symbol": "601818", "name": "光大银行", "industry": "银行", "sector": "金融"},
    {"symbol": "002142", "name": "宁波银行", "industry": "银行", "sector": "金融"},
    {"symbol": "600919", "name": "江苏银行", "industry": "银行", "sector": "金融"},
    {"symbol": "601169", "name": "北京银行", "industry": "银行", "sector": "金融"},
    {"symbol": "002839", "name": "张家港行", "industry": "银行", "sector": "金融"},
    {"symbol": "600926", "name": "杭州银行", "industry": "银行", "sector": "金融"},

    # ===== 保险/证券 =====
    {"symbol": "601318", "name": "中国平安", "industry": "保险", "sector": "金融"},
    {"symbol": "601628", "name": "中国人寿", "industry": "保险", "sector": "金融"},
    {"symbol": "601601", "name": "中国太保", "industry": "保险", "sector": "金融"},
    {"symbol": "002736", "name": "国信证券", "industry": "证券", "sector": "金融"},
    {"symbol": "600030", "name": "中信证券", "industry": "证券", "sector": "金融"},
    {"symbol": "601211", "name": "国泰君安", "industry": "证券", "sector": "金融"},
    {"symbol": "600837", "name": "海通证券", "industry": "证券", "sector": "金融"},
    {"symbol": "000776", "name": "广发证券", "industry": "证券", "sector": "金融"},
    {"symbol": "601688", "name": "华泰证券", "industry": "证券", "sector": "金融"},
    {"symbol": "600958", "name": "东方证券", "industry": "证券", "sector": "金融"},
    {"symbol": "300059", "name": "东方财富", "industry": "金融科技", "sector": "金融"},

    # ===== 电池/新能源 =====
    {"symbol": "300750", "name": "宁德时代", "industry": "电池", "sector": "新能源"},
    {"symbol": "002594", "name": "比亚迪", "industry": "新能源汽车", "sector": "新能源"},
    {"symbol": "601012", "name": "隆基绿能", "industry": "光伏", "sector": "新能源"},
    {"symbol": "600438", "name": "通威股份", "industry": "光伏", "sector": "新能源"},
    {"symbol": "002459", "name": "晶澳科技", "industry": "光伏", "sector": "新能源"},
    {"symbol": "688599", "name": "天合光能", "industry": "光伏", "sector": "新能源"},
    {"symbol": "300274", "name": "阳光电源", "industry": "逆变器", "sector": "新能源"},
    {"symbol": "002709", "name": "天赐材料", "industry": "电解液", "sector": "新能源"},
    {"symbol": "300014", "name": "亿纬锂能", "industry": "电池", "sector": "新能源"},
    {"symbol": "002812", "name": "恩捷股份", "industry": "隔膜", "sector": "新能源"},
    {"symbol": "300763", "name": "锦浪科技", "industry": "逆变器", "sector": "新能源"},
    {"symbol": "688390", "name": "固德威", "industry": "逆变器", "sector": "新能源"},

    # ===== 半导体/芯片 =====
    {"symbol": "688981", "name": "中芯国际", "industry": "晶圆代工", "sector": "科技"},
    {"symbol": "002371", "name": "北方华创", "industry": "半导体设备", "sector": "科技"},
    {"symbol": "688012", "name": "中微公司", "industry": "半导体设备", "sector": "科技"},
    {"symbol": "603501", "name": "韦尔股份", "industry": "芯片设计", "sector": "科技"},
    {"symbol": "300782", "name": "卓胜微", "industry": "射频芯片", "sector": "科技"},
    {"symbol": "688008", "name": "澜起科技", "industry": "内存接口", "sector": "科技"},
    {"symbol": "002049", "name": "紫光国微", "industry": "安全芯片", "sector": "科技"},
    {"symbol": "688036", "name": "传音控股", "industry": "手机", "sector": "科技"},
    {"symbol": "300661", "name": "圣邦股份", "industry": "模拟芯片", "sector": "科技"},
    {"symbol": "688120", "name": "华海清科", "industry": "半导体设备", "sector": "科技"},

    # ===== 消费电子/科技 =====
    {"symbol": "002475", "name": "立讯精密", "industry": "消费电子", "sector": "科技"},
    {"symbol": "002415", "name": "海康威视", "industry": "安防", "sector": "科技"},
    {"symbol": "002241", "name": "歌尔股份", "industry": "声学", "sector": "科技"},
    {"symbol": "603160", "name": "汇顶科技", "industry": "指纹芯片", "sector": "科技"},
    {"symbol": "300433", "name": "蓝思科技", "industry": "玻璃盖板", "sector": "科技"},
    {"symbol": "002600", "name": "领益智造", "industry": "精密件", "sector": "科技"},

    # ===== 软件/互联网 =====
    {"symbol": "002230", "name": "科大讯飞", "industry": "AI语音", "sector": "科技"},
    {"symbol": "688111", "name": "金山办公", "industry": "办公软件", "sector": "科技"},
    {"symbol": "300033", "name": "同花顺", "industry": "金融IT", "sector": "科技"},
    {"symbol": "002410", "name": "广联达", "industry": "建筑IT", "sector": "科技"},
    {"symbol": "300496", "name": "中科创达", "industry": "操作系统", "sector": "科技"},
    {"symbol": "688088", "name": "虹软科技", "industry": "视觉AI", "sector": "科技"},

    # ===== 通信 =====
    {"symbol": "000063", "name": "中兴通讯", "industry": "通信设备", "sector": "科技"},
    {"symbol": "600941", "name": "中国移动", "industry": "运营商", "sector": "科技"},
    {"symbol": "601728", "name": "中国电信", "industry": "运营商", "sector": "科技"},
    {"symbol": "600050", "name": "中国联通", "industry": "运营商", "sector": "科技"},

    # ===== 医药 =====
    {"symbol": "600276", "name": "恒瑞医药", "industry": "创新药", "sector": "医药"},
    {"symbol": "603259", "name": "药明康德", "industry": "CXO", "sector": "医药"},
    {"symbol": "300760", "name": "迈瑞医疗", "industry": "医疗器械", "sector": "医药"},
    {"symbol": "000538", "name": "云南白药", "industry": "中药", "sector": "医药"},
    {"symbol": "600196", "name": "复星医药", "industry": "综合药企", "sector": "医药"},
    {"symbol": "002007", "name": "华兰生物", "industry": "血液制品", "sector": "医药"},
    {"symbol": "300015", "name": "爱尔眼科", "industry": "眼科连锁", "sector": "医药"},
    {"symbol": "300122", "name": "智飞生物", "industry": "疫苗", "sector": "医药"},
    {"symbol": "000661", "name": "长春高新", "industry": "生长激素", "sector": "医药"},
    {"symbol": "300347", "name": "泰格医药", "industry": "CRO", "sector": "医药"},
    {"symbol": "688180", "name": "君实生物", "industry": "创新药", "sector": "医药"},
    {"symbol": "002001", "name": "新和成", "industry": "维生素", "sector": "医药"},
    {"symbol": "600085", "name": "同仁堂", "industry": "中药", "sector": "医药"},
    {"symbol": "002241", "name": "歌尔股份", "industry": "声学", "sector": "科技"},
    {"symbol": "300529", "name": "健帆生物", "industry": "血液净化", "sector": "医药"},

    # ===== 电力/公用事业 =====
    {"symbol": "600900", "name": "长江电力", "industry": "水电", "sector": "公用事业"},
    {"symbol": "600886", "name": "国投电力", "industry": "水电", "sector": "公用事业"},
    {"symbol": "601985", "name": "中国核电", "industry": "核电", "sector": "公用事业"},
    {"symbol": "600023", "name": "浙能电力", "industry": "火电", "sector": "公用事业"},
    {"symbol": "600011", "name": "华能国际", "industry": "火电", "sector": "公用事业"},
    {"symbol": "003816", "name": "中国广核", "industry": "核电", "sector": "公用事业"},

    # ===== 汽车 =====
    {"symbol": "600104", "name": "上汽集团", "industry": "汽车", "sector": "工业"},
    {"symbol": "000625", "name": "长安汽车", "industry": "汽车", "sector": "工业"},
    {"symbol": "601238", "name": "广汽集团", "industry": "汽车", "sector": "工业"},
    {"symbol": "600741", "name": "华域汽车", "industry": "汽车零部件", "sector": "工业"},
    {"symbol": "002920", "name": "德赛西威", "industry": "智能驾驶", "sector": "工业"},
    {"symbol": "300750", "name": "宁德时代", "industry": "电池", "sector": "新能源"},

    # ===== 地产 =====
    {"symbol": "001979", "name": "招商蛇口", "industry": "房地产", "sector": "地产"},
    {"symbol": "600048", "name": "保利发展", "industry": "房地产", "sector": "地产"},
    {"symbol": "000002", "name": "万科A", "industry": "房地产", "sector": "地产"},
    {"symbol": "600383", "name": "金地集团", "industry": "房地产", "sector": "地产"},

    # ===== 钢铁/有色 =====
    {"symbol": "600019", "name": "宝钢股份", "industry": "钢铁", "sector": "工业"},
    {"symbol": "601899", "name": "紫金矿业", "industry": "黄金", "sector": "工业"},
    {"symbol": "603799", "name": "华友钴业", "industry": "钴", "sector": "新能源"},
    {"symbol": "002460", "name": "赣锋锂业", "industry": "锂", "sector": "新能源"},
    {"symbol": "002466", "name": "天齐锂业", "industry": "锂", "sector": "新能源"},

    # ===== 建材/化工 =====
    {"symbol": "600585", "name": "海螺水泥", "industry": "水泥", "sector": "工业"},
    {"symbol": "002271", "name": "东方雨虹", "industry": "防水材料", "sector": "工业"},
    {"symbol": "600309", "name": "万华化学", "industry": "MDI", "sector": "工业"},
    {"symbol": "000786", "name": "北新建材", "industry": "石膏板", "sector": "工业"},

    # ===== 军工 =====
    {"symbol": "600760", "name": "中航沈飞", "industry": "战斗机", "sector": "军工"},
    {"symbol": "601989", "name": "中国重工", "industry": "船舶", "sector": "军工"},
    {"symbol": "002179", "name": "中航光电", "industry": "连接器", "sector": "军工"},
    {"symbol": "600893", "name": "航发动力", "industry": "航空发动机", "sector": "军工"},
    {"symbol": "002414", "name": "高德红外", "industry": "红外", "sector": "军工"},

    # ===== 交通运输 =====
    {"symbol": "601006", "name": "大秦铁路", "industry": "铁路", "sector": "交运"},
    {"symbol": "600009", "name": "上海机场", "industry": "机场", "sector": "交运"},
    {"symbol": "000089", "name": "深圳机场", "industry": "机场", "sector": "交运"},
    {"symbol": "601111", "name": "中国国航", "industry": "航空", "sector": "交运"},
    {"symbol": "600029", "name": "南方航空", "industry": "航空", "sector": "交运"},

    # ===== 传媒 =====
    {"symbol": "300413", "name": "芒果超媒", "industry": "视频", "sector": "传媒"},
    {"symbol": "002027", "name": "分众传媒", "industry": "广告", "sector": "传媒"},
    {"symbol": "300251", "name": "光线传媒", "industry": "影视", "sector": "传媒"},

    # ===== 环保 =====
    {"symbol": "300070", "name": "碧水源", "industry": "水处理", "sector": "环保"},
    {"symbol": "603568", "name": "伟明环保", "industry": "垃圾焚烧", "sector": "环保"},

    # ===== 免税/旅游 =====
    {"symbol": "601888", "name": "中国中免", "industry": "免税", "sector": "消费"},
    {"symbol": "000888", "name": "峨眉山A", "industry": "旅游", "sector": "消费"},
    {"symbol": "600138", "name": "中青旅", "industry": "旅游", "sector": "消费"},

    # ===== 其他消费 =====
    {"symbol": "600655", "name": "豫园股份", "industry": "综合", "sector": "消费"},
    {"symbol": "002714", "name": "牧原股份", "industry": "生猪", "sector": "消费"},
    {"symbol": "300498", "name": "温氏股份", "industry": "生猪", "sector": "消费"},
    {"symbol": "002311", "name": "海大集团", "industry": "饲料", "sector": "消费"},
    {"symbol": "600436", "name": "片仔癀", "industry": "中药", "sector": "医药"},
    {"symbol": "000568", "name": "泸州老窖", "industry": "白酒", "sector": "消费"},

    # ===== 互联网/平台 =====
    {"symbol": "002027", "name": "分众传媒", "industry": "广告", "sector": "传媒"},
    {"symbol": "603039", "name": "泛微网络", "industry": "协同办公", "sector": "科技"},
    {"symbol": "300059", "name": "东方财富", "industry": "金融IT", "sector": "金融"},
    {"symbol": "002230", "name": "科大讯飞", "industry": "AI语音", "sector": "科技"},

    # ===== 充电桩/储能 =====
    {"symbol": "300617", "name": "安靠智电", "industry": "电缆", "sector": "新能源"},
    {"symbol": "300687", "name": "赛意信息", "industry": "工业软件", "sector": "科技"},
    {"symbol": "002129", "name": "TCL中环", "industry": "光伏硅片", "sector": "新能源"},

    # ===== 机器人/自动化 =====
    {"symbol": "300124", "name": "汇川技术", "industry": "工控", "sector": "工业"},
    {"symbol": "688169", "name": "石头科技", "industry": "扫地机器人", "sector": "消费"},
    {"symbol": "002747", "name": "埃斯顿", "industry": "工业机器人", "sector": "工业"},
    {"symbol": "300073", "name": "当升科技", "industry": "正极材料", "sector": "新能源"},

    # ===== 低位补涨标的 =====
    {"symbol": "601669", "name": "中国电建", "industry": "建筑", "sector": "工业"},
    {"symbol": "601668", "name": "中国建筑", "industry": "建筑", "sector": "工业"},
    {"symbol": "601390", "name": "中国中铁", "industry": "基建", "sector": "工业"},
    {"symbol": "601186", "name": "中国铁建", "industry": "基建", "sector": "工业"},
    {"symbol": "600585", "name": "海螺水泥", "industry": "水泥", "sector": "工业"},
    {"symbol": "601766", "name": "中国中车", "industry": "轨交", "sector": "工业"},
    {"symbol": "601111", "name": "中国国航", "industry": "航空", "sector": "交运"},

    # ===== 补充 A 股标的（凑满 200+） =====
    {"symbol": "600690", "name": "海尔智家", "industry": "家电", "sector": "消费"},
    {"symbol": "601888", "name": "中国中免", "industry": "免税", "sector": "消费"},
    {"symbol": "603288", "name": "海天味业", "industry": "调味品", "sector": "消费"},
    {"symbol": "300124", "name": "汇川技术", "industry": "工控", "sector": "工业"},
    {"symbol": "688169", "name": "石头科技", "industry": "扫地机器人", "sector": "消费"},
    {"symbol": "002747", "name": "埃斯顿", "industry": "工业机器人", "sector": "工业"},
    {"symbol": "300073", "name": "当升科技", "industry": "正极材料", "sector": "新能源"},
    {"symbol": "002129", "name": "TCL中环", "industry": "光伏硅片", "sector": "新能源"},
    {"symbol": "300617", "name": "安靠智电", "industry": "电缆", "sector": "新能源"},
    {"symbol": "601899", "name": "紫金矿业", "industry": "黄金", "sector": "工业"},
    {"symbol": "002460", "name": "赣锋锂业", "industry": "锂", "sector": "新能源"},
    {"symbol": "002466", "name": "天齐锂业", "industry": "锂", "sector": "新能源"},
    {"symbol": "603799", "name": "华友钴业", "industry": "钴", "sector": "新能源"},
    {"symbol": "600309", "name": "万华化学", "industry": "MDI", "sector": "工业"},
    {"symbol": "002271", "name": "东方雨虹", "industry": "防水材料", "sector": "工业"},
    {"symbol": "000786", "name": "北新建材", "industry": "石膏板", "sector": "工业"},
    {"symbol": "600760", "name": "中航沈飞", "industry": "战斗机", "sector": "军工"},
    {"symbol": "601989", "name": "中国重工", "industry": "船舶", "sector": "军工"},
    {"symbol": "002179", "name": "中航光电", "industry": "连接器", "sector": "军工"},
    {"symbol": "600893", "name": "航发动力", "industry": "航空发动机", "sector": "军工"},
    {"symbol": "002414", "name": "高德红外", "industry": "红外", "sector": "军工"},
    {"symbol": "601006", "name": "大秦铁路", "industry": "铁路", "sector": "交运"},
    {"symbol": "600009", "name": "上海机场", "industry": "机场", "sector": "交运"},
    {"symbol": "000089", "name": "深圳机场", "industry": "机场", "sector": "交运"},
    {"symbol": "600029", "name": "南方航空", "industry": "航空", "sector": "交运"},
    {"symbol": "300413", "name": "芒果超媒", "industry": "视频", "sector": "传媒"},
    {"symbol": "002027", "name": "分众传媒", "industry": "广告", "sector": "传媒"},
    {"symbol": "300251", "name": "光线传媒", "industry": "影视", "sector": "传媒"},
    {"symbol": "300070", "name": "碧水源", "industry": "水处理", "sector": "环保"},
    {"symbol": "603568", "name": "伟明环保", "industry": "垃圾焚烧", "sector": "环保"},
    {"symbol": "002714", "name": "牧原股份", "industry": "生猪", "sector": "消费"},
    {"symbol": "300498", "name": "温氏股份", "industry": "生猪", "sector": "消费"},
    {"symbol": "002311", "name": "海大集团", "industry": "饲料", "sector": "消费"},
    {"symbol": "600436", "name": "片仔癀", "industry": "中药", "sector": "医药"},
    {"symbol": "601318", "name": "中国平安", "industry": "保险", "sector": "金融"},
    {"symbol": "601628", "name": "中国人寿", "industry": "保险", "sector": "金融"},
    {"symbol": "601601", "name": "中国太保", "industry": "保险", "sector": "金融"},
    {"symbol": "601398", "name": "工商银行", "industry": "银行", "sector": "金融"},
    {"symbol": "601939", "name": "建设银行", "industry": "银行", "sector": "金融"},
    {"symbol": "601288", "name": "农业银行", "industry": "银行", "sector": "金融"},
    {"symbol": "601988", "name": "中国银行", "industry": "银行", "sector": "金融"},
    {"symbol": "600000", "name": "浦发银行", "industry": "银行", "sector": "金融"},
    {"symbol": "600016", "name": "民生银行", "industry": "银行", "sector": "金融"},
    {"symbol": "601818", "name": "光大银行", "industry": "银行", "sector": "金融"},
    {"symbol": "002142", "name": "宁波银行", "industry": "银行", "sector": "金融"},
    {"symbol": "600919", "name": "江苏银行", "industry": "银行", "sector": "金融"},
    {"symbol": "601169", "name": "北京银行", "industry": "银行", "sector": "金融"},
    {"symbol": "600926", "name": "杭州银行", "industry": "银行", "sector": "金融"},
    {"symbol": "601211", "name": "国泰君安", "industry": "证券", "sector": "金融"},
    {"symbol": "600837", "name": "海通证券", "industry": "证券", "sector": "金融"},
    {"symbol": "000776", "name": "广发证券", "industry": "证券", "sector": "金融"},
    {"symbol": "601688", "name": "华泰证券", "industry": "证券", "sector": "金融"},
    {"symbol": "600958", "name": "东方证券", "industry": "证券", "sector": "金融"},
    {"symbol": "002736", "name": "国信证券", "industry": "证券", "sector": "金融"},
    {"symbol": "600030", "name": "中信证券", "industry": "证券", "sector": "金融"},
    {"symbol": "601012", "name": "隆基绿能", "industry": "光伏", "sector": "新能源"},
    {"symbol": "600438", "name": "通威股份", "industry": "光伏", "sector": "新能源"},
    {"symbol": "002459", "name": "晶澳科技", "industry": "光伏", "sector": "新能源"},
    {"symbol": "688599", "name": "天合光能", "industry": "光伏", "sector": "新能源"},
    {"symbol": "300274", "name": "阳光电源", "industry": "逆变器", "sector": "新能源"},
    {"symbol": "002709", "name": "天赐材料", "industry": "电解液", "sector": "新能源"},
    {"symbol": "300014", "name": "亿纬锂能", "industry": "电池", "sector": "新能源"},
    {"symbol": "002812", "name": "恩捷股份", "industry": "隔膜", "sector": "新能源"},
    {"symbol": "300763", "name": "锦浪科技", "industry": "逆变器", "sector": "新能源"},
    {"symbol": "688390", "name": "固德威", "industry": "逆变器", "sector": "新能源"},
    {"symbol": "688981", "name": "中芯国际", "industry": "晶圆代工", "sector": "科技"},
    {"symbol": "002371", "name": "北方华创", "industry": "半导体设备", "sector": "科技"},
    {"symbol": "688012", "name": "中微公司", "industry": "半导体设备", "sector": "科技"},
    {"symbol": "603501", "name": "韦尔股份", "industry": "芯片设计", "sector": "科技"},
    {"symbol": "300782", "name": "卓胜微", "industry": "射频芯片", "sector": "科技"},
    {"symbol": "688008", "name": "澜起科技", "industry": "内存接口", "sector": "科技"},
    {"symbol": "002049", "name": "紫光国微", "industry": "安全芯片", "sector": "科技"},
    {"symbol": "688036", "name": "传音控股", "industry": "手机", "sector": "科技"},
    {"symbol": "300661", "name": "圣邦股份", "industry": "模拟芯片", "sector": "科技"},
    {"symbol": "688120", "name": "华海清科", "industry": "半导体设备", "sector": "科技"},
    {"symbol": "002475", "name": "立讯精密", "industry": "消费电子", "sector": "科技"},
    {"symbol": "002415", "name": "海康威视", "industry": "安防", "sector": "科技"},
    {"symbol": "002241", "name": "歌尔股份", "industry": "声学", "sector": "科技"},
    {"symbol": "002230", "name": "科大讯飞", "industry": "AI语音", "sector": "科技"},
    {"symbol": "688111", "name": "金山办公", "industry": "办公软件", "sector": "科技"},
    {"symbol": "300033", "name": "同花顺", "industry": "金融IT", "sector": "科技"},
    {"symbol": "002410", "name": "广联达", "industry": "建筑IT", "sector": "科技"},
    {"symbol": "300496", "name": "中科创达", "industry": "操作系统", "sector": "科技"},
    {"symbol": "000063", "name": "中兴通讯", "industry": "通信设备", "sector": "科技"},
    {"symbol": "600941", "name": "中国移动", "industry": "运营商", "sector": "科技"},
    {"symbol": "601728", "name": "中国电信", "industry": "运营商", "sector": "科技"},
    {"symbol": "600050", "name": "中国联通", "industry": "运营商", "sector": "科技"},
    {"symbol": "600276", "name": "恒瑞医药", "industry": "创新药", "sector": "医药"},
    {"symbol": "603259", "name": "药明康德", "industry": "CXO", "sector": "医药"},
    {"symbol": "300760", "name": "迈瑞医疗", "industry": "医疗器械", "sector": "医药"},
    {"symbol": "000538", "name": "云南白药", "industry": "中药", "sector": "医药"},
    {"symbol": "600196", "name": "复星医药", "industry": "综合药企", "sector": "医药"},
    {"symbol": "002007", "name": "华兰生物", "industry": "血液制品", "sector": "医药"},
    {"symbol": "300015", "name": "爱尔眼科", "industry": "眼科连锁", "sector": "医药"},
    {"symbol": "300122", "name": "智飞生物", "industry": "疫苗", "sector": "医药"},
    {"symbol": "000661", "name": "长春高新", "industry": "生长激素", "sector": "医药"},
    {"symbol": "300347", "name": "泰格医药", "industry": "CRO", "sector": "医药"},
    {"symbol": "688180", "name": "君实生物", "industry": "创新药", "sector": "医药"},
    {"symbol": "002001", "name": "新和成", "industry": "维生素", "sector": "医药"},
    {"symbol": "600085", "name": "同仁堂", "industry": "中药", "sector": "医药"},
    {"symbol": "300529", "name": "健帆生物", "industry": "血液净化", "sector": "医药"},
    {"symbol": "600900", "name": "长江电力", "industry": "水电", "sector": "公用事业"},
    {"symbol": "600886", "name": "国投电力", "industry": "水电", "sector": "公用事业"},
    {"symbol": "601985", "name": "中国核电", "industry": "核电", "sector": "公用事业"},
    {"symbol": "600023", "name": "浙能电力", "industry": "火电", "sector": "公用事业"},
    {"symbol": "600011", "name": "华能国际", "industry": "火电", "sector": "公用事业"},
    {"symbol": "003816", "name": "中国广核", "industry": "核电", "sector": "公用事业"},
    {"symbol": "600104", "name": "上汽集团", "industry": "汽车", "sector": "工业"},
    {"symbol": "000625", "name": "长安汽车", "industry": "汽车", "sector": "工业"},
    {"symbol": "601238", "name": "广汽集团", "industry": "汽车", "sector": "工业"},
    {"symbol": "600741", "name": "华域汽车", "industry": "汽车零部件", "sector": "工业"},
    {"symbol": "002920", "name": "德赛西威", "industry": "智能驾驶", "sector": "工业"},
    {"symbol": "001979", "name": "招商蛇口", "industry": "房地产", "sector": "地产"},
    {"symbol": "600048", "name": "保利发展", "industry": "房地产", "sector": "地产"},
    {"symbol": "000002", "name": "万科A", "industry": "房地产", "sector": "地产"},
    {"symbol": "600383", "name": "金地集团", "industry": "房地产", "sector": "地产"},
    {"symbol": "600019", "name": "宝钢股份", "industry": "钢铁", "sector": "工业"},
    {"symbol": "603290", "name": "斯达半导", "industry": "IGBT", "sector": "科技"},
    {"symbol": "688256", "name": "寒武纪", "industry": "AI芯片", "sector": "科技"},
    {"symbol": "301358", "name": "湖南裕能", "industry": "正极材料", "sector": "新能源"},
    {"symbol": "600036", "name": "招商银行", "industry": "银行", "sector": "金融"},
    {"symbol": "000001", "name": "平安银行", "industry": "银行", "sector": "金融"},
    {"symbol": "601166", "name": "兴业银行", "industry": "银行", "sector": "金融"},
    {"symbol": "300750", "name": "宁德时代", "industry": "电池", "sector": "新能源"},
    {"symbol": "002594", "name": "比亚迪", "industry": "新能源汽车", "sector": "新能源"},
    {"symbol": "000651", "name": "格力电器", "industry": "空调", "sector": "消费"},
    {"symbol": "000333", "name": "美的集团", "industry": "家电", "sector": "消费"},
    {"symbol": "002304", "name": "洋河股份", "industry": "白酒", "sector": "消费"},
    {"symbol": "600809", "name": "山西汾酒", "industry": "白酒", "sector": "消费"},
    {"symbol": "000568", "name": "泸州老窖", "industry": "白酒", "sector": "消费"},
    {"symbol": "600887", "name": "伊利股份", "industry": "乳制品", "sector": "消费"},
    {"symbol": "300059", "name": "东方财富", "industry": "金融科技", "sector": "金融"},
    {"symbol": "600585", "name": "海螺水泥", "industry": "水泥", "sector": "工业"},

    # ===== 更多 A 股标的 =====
    {"symbol": "600436", "name": "片仔癀", "industry": "中药", "sector": "医药"},
    {"symbol": "600196", "name": "复星医药", "industry": "综合药企", "sector": "医药"},
    {"symbol": "002007", "name": "华兰生物", "industry": "血液制品", "sector": "医药"},
    {"symbol": "300015", "name": "爱尔眼科", "industry": "眼科连锁", "sector": "医药"},
    {"symbol": "300122", "name": "智飞生物", "industry": "疫苗", "sector": "医药"},
    {"symbol": "000661", "name": "长春高新", "industry": "生长激素", "sector": "医药"},
    {"symbol": "300347", "name": "泰格医药", "industry": "CRO", "sector": "医药"},
    {"symbol": "600085", "name": "同仁堂", "industry": "中药", "sector": "医药"},
    {"symbol": "300529", "name": "健帆生物", "industry": "血液净化", "sector": "医药"},
    {"symbol": "000538", "name": "云南白药", "industry": "中药", "sector": "医药"},
    {"symbol": "601628", "name": "中国人寿", "industry": "保险", "sector": "金融"},
    {"symbol": "601601", "name": "中国太保", "industry": "保险", "sector": "金融"},
    {"symbol": "002736", "name": "国信证券", "industry": "证券", "sector": "金融"},
    {"symbol": "600030", "name": "中信证券", "industry": "证券", "sector": "金融"},
    {"symbol": "601211", "name": "国泰君安", "industry": "证券", "sector": "金融"},
    {"symbol": "600837", "name": "海通证券", "industry": "证券", "sector": "金融"},
    {"symbol": "000776", "name": "广发证券", "industry": "证券", "sector": "金融"},
    {"symbol": "601688", "name": "华泰证券", "industry": "证券", "sector": "金融"},
    {"symbol": "600958", "name": "东方证券", "industry": "证券", "sector": "金融"},
    {"symbol": "300059", "name": "东方财富", "industry": "金融科技", "sector": "金融"},
    {"symbol": "002475", "name": "立讯精密", "industry": "消费电子", "sector": "科技"},
    {"symbol": "002415", "name": "海康威视", "industry": "安防", "sector": "科技"},
    {"symbol": "002241", "name": "歌尔股份", "industry": "声学", "sector": "科技"},
    {"symbol": "603160", "name": "汇顶科技", "industry": "指纹芯片", "sector": "科技"},
    {"symbol": "300433", "name": "蓝思科技", "industry": "玻璃盖板", "sector": "科技"},
    {"symbol": "002600", "name": "领益智造", "industry": "精密件", "sector": "科技"},
    {"symbol": "002230", "name": "科大讯飞", "industry": "AI语音", "sector": "科技"},
    {"symbol": "688111", "name": "金山办公", "industry": "办公软件", "sector": "科技"},
    {"symbol": "300033", "name": "同花顺", "industry": "金融IT", "sector": "科技"},
    {"symbol": "002410", "name": "广联达", "industry": "建筑IT", "sector": "科技"},
    {"symbol": "300496", "name": "中科创达", "industry": "操作系统", "sector": "科技"},
    {"symbol": "000063", "name": "中兴通讯", "industry": "通信设备", "sector": "科技"},
    {"symbol": "600941", "name": "中国移动", "industry": "运营商", "sector": "科技"},
    {"symbol": "601728", "name": "中国电信", "industry": "运营商", "sector": "科技"},
    {"symbol": "600050", "name": "中国联通", "industry": "运营商", "sector": "科技"},
    {"symbol": "601899", "name": "紫金矿业", "industry": "黄金", "sector": "工业"},
    {"symbol": "002460", "name": "赣锋锂业", "industry": "锂", "sector": "新能源"},
    {"symbol": "002466", "name": "天齐锂业", "industry": "锂", "sector": "新能源"},
    {"symbol": "603799", "name": "华友钴业", "industry": "钴", "sector": "新能源"},
    {"symbol": "600309", "name": "万华化学", "industry": "MDI", "sector": "工业"},
    {"symbol": "002271", "name": "东方雨虹", "industry": "防水材料", "sector": "工业"},
    {"symbol": "000786", "name": "北新建材", "industry": "石膏板", "sector": "工业"},
    {"symbol": "600760", "name": "中航沈飞", "industry": "战斗机", "sector": "军工"},
    {"symbol": "601989", "name": "中国重工", "industry": "船舶", "sector": "军工"},
    {"symbol": "002179", "name": "中航光电", "industry": "连接器", "sector": "军工"},
    {"symbol": "600893", "name": "航发动力", "industry": "航空发动机", "sector": "军工"},
    {"symbol": "002414", "name": "高德红外", "industry": "红外", "sector": "军工"},
    {"symbol": "601006", "name": "大秦铁路", "industry": "铁路", "sector": "交运"},
    {"symbol": "600009", "name": "上海机场", "industry": "机场", "sector": "交运"},
    {"symbol": "000089", "name": "深圳机场", "industry": "机场", "sector": "交运"},
    {"symbol": "601111", "name": "中国国航", "industry": "航空", "sector": "交运"},
    {"symbol": "600029", "name": "南方航空", "industry": "航空", "sector": "交运"},
    {"symbol": "300413", "name": "芒果超媒", "industry": "视频", "sector": "传媒"},
    {"symbol": "002027", "name": "分众传媒", "industry": "广告", "sector": "传媒"},
    {"symbol": "300251", "name": "光线传媒", "industry": "影视", "sector": "传媒"},
    {"symbol": "300070", "name": "碧水源", "industry": "水处理", "sector": "环保"},
    {"symbol": "603568", "name": "伟明环保", "industry": "垃圾焚烧", "sector": "环保"},
    {"symbol": "002714", "name": "牧原股份", "industry": "生猪", "sector": "消费"},
    {"symbol": "300498", "name": "温氏股份", "industry": "生猪", "sector": "消费"},
    {"symbol": "002311", "name": "海大集团", "industry": "饲料", "sector": "消费"},
    {"symbol": "001979", "name": "招商蛇口", "industry": "房地产", "sector": "地产"},
    {"symbol": "600048", "name": "保利发展", "industry": "房地产", "sector": "地产"},
    {"symbol": "000002", "name": "万科A", "industry": "房地产", "sector": "地产"},
    {"symbol": "600383", "name": "金地集团", "industry": "房地产", "sector": "地产"},
    {"symbol": "600019", "name": "宝钢股份", "industry": "钢铁", "sector": "工业"},
    {"symbol": "600104", "name": "上汽集团", "industry": "汽车", "sector": "工业"},
    {"symbol": "000625", "name": "长安汽车", "industry": "汽车", "sector": "工业"},
    {"symbol": "601238", "name": "广汽集团", "industry": "汽车", "sector": "工业"},
    {"symbol": "600741", "name": "华域汽车", "industry": "汽车零部件", "sector": "工业"},
    {"symbol": "002920", "name": "德赛西威", "industry": "智能驾驶", "sector": "工业"},
    {"symbol": "601669", "name": "中国电建", "industry": "建筑", "sector": "工业"},
    {"symbol": "601668", "name": "中国建筑", "industry": "建筑", "sector": "工业"},
    {"symbol": "601390", "name": "中国中铁", "industry": "基建", "sector": "工业"},
    {"symbol": "601186", "name": "中国铁建", "industry": "基建", "sector": "工业"},
    {"symbol": "601766", "name": "中国中车", "industry": "轨交", "sector": "工业"},
    {"symbol": "300124", "name": "汇川技术", "industry": "工控", "sector": "工业"},
    {"symbol": "688169", "name": "石头科技", "industry": "扫地机器人", "sector": "消费"},
    {"symbol": "002747", "name": "埃斯顿", "industry": "工业机器人", "sector": "工业"},
    {"symbol": "300073", "name": "当升科技", "industry": "正极材料", "sector": "新能源"},
    {"symbol": "002129", "name": "TCL中环", "industry": "光伏硅片", "sector": "新能源"},
    {"symbol": "300617", "name": "安靠智电", "industry": "电缆", "sector": "新能源"},
    {"symbol": "600900", "name": "长江电力", "industry": "水电", "sector": "公用事业"},
    {"symbol": "600886", "name": "国投电力", "industry": "水电", "sector": "公用事业"},
    {"symbol": "601985", "name": "中国核电", "industry": "核电", "sector": "公用事业"},
    {"symbol": "600023", "name": "浙能电力", "industry": "火电", "sector": "公用事业"},
    {"symbol": "600011", "name": "华能国际", "industry": "火电", "sector": "公用事业"},
    {"symbol": "003816", "name": "中国广核", "industry": "核电", "sector": "公用事业"},

    # ===== 更多 A 股（凑满 250+） =====
    {"symbol": "600519", "name": "贵州茅台", "industry": "白酒", "sector": "消费"},
    {"symbol": "000858", "name": "五粮液", "industry": "白酒", "sector": "消费"},
    {"symbol": "000568", "name": "泸州老窖", "industry": "白酒", "sector": "消费"},
    {"symbol": "002304", "name": "洋河股份", "industry": "白酒", "sector": "消费"},
    {"symbol": "600809", "name": "山西汾酒", "industry": "白酒", "sector": "消费"},
    {"symbol": "000596", "name": "古井贡酒", "industry": "白酒", "sector": "消费"},
    {"symbol": "603369", "name": "今世缘", "industry": "白酒", "sector": "消费"},
    {"symbol": "600779", "name": "水井坊", "industry": "白酒", "sector": "消费"},
    {"symbol": "000799", "name": "酒鬼酒", "industry": "白酒", "sector": "消费"},
    {"symbol": "603589", "name": "口子窖", "industry": "白酒", "sector": "消费"},
    {"symbol": "600887", "name": "伊利股份", "industry": "乳制品", "sector": "消费"},
    {"symbol": "603288", "name": "海天味业", "industry": "调味品", "sector": "消费"},
    {"symbol": "600882", "name": "妙可蓝多", "industry": "乳制品", "sector": "消费"},
    {"symbol": "002557", "name": "洽洽食品", "industry": "休闲食品", "sector": "消费"},
    {"symbol": "603517", "name": "绝味食品", "industry": "卤制品", "sector": "消费"},
    {"symbol": "002507", "name": "涪陵榨菜", "industry": "调味品", "sector": "消费"},
    {"symbol": "603027", "name": "千禾味业", "industry": "调味品", "sector": "消费"},
    {"symbol": "600597", "name": "光明乳业", "industry": "乳制品", "sector": "消费"},
    {"symbol": "000895", "name": "双汇发展", "industry": "肉制品", "sector": "消费"},
    {"symbol": "600600", "name": "青岛啤酒", "industry": "啤酒", "sector": "消费"},
    {"symbol": "600132", "name": "重庆啤酒", "industry": "啤酒", "sector": "消费"},
    {"symbol": "000651", "name": "格力电器", "industry": "空调", "sector": "消费"},
    {"symbol": "000333", "name": "美的集团", "industry": "家电", "sector": "消费"},
    {"symbol": "002032", "name": "苏泊尔", "industry": "小家电", "sector": "消费"},
    {"symbol": "002508", "name": "老板电器", "industry": "厨电", "sector": "消费"},
    {"symbol": "603486", "name": "科沃斯", "industry": "扫地机器人", "sector": "消费"},
    {"symbol": "002242", "name": "九阳股份", "industry": "小家电", "sector": "消费"},
    {"symbol": "600060", "name": "海信视像", "industry": "黑电", "sector": "消费"},
    {"symbol": "600398", "name": "海澜之家", "industry": "男装", "sector": "消费"},
    {"symbol": "002563", "name": "森马服饰", "industry": "休闲服饰", "sector": "消费"},
    {"symbol": "603877", "name": "太平鸟", "industry": "时尚服饰", "sector": "消费"},
    {"symbol": "600036", "name": "招商银行", "industry": "银行", "sector": "金融"},
    {"symbol": "000001", "name": "平安银行", "industry": "银行", "sector": "金融"},
    {"symbol": "601166", "name": "兴业银行", "industry": "银行", "sector": "金融"},
    {"symbol": "601398", "name": "工商银行", "industry": "银行", "sector": "金融"},
    {"symbol": "601939", "name": "建设银行", "industry": "银行", "sector": "金融"},
    {"symbol": "601288", "name": "农业银行", "industry": "银行", "sector": "金融"},
    {"symbol": "601988", "name": "中国银行", "industry": "银行", "sector": "金融"},
    {"symbol": "600000", "name": "浦发银行", "industry": "银行", "sector": "金融"},
    {"symbol": "600016", "name": "民生银行", "industry": "银行", "sector": "金融"},
    {"symbol": "601818", "name": "光大银行", "industry": "银行", "sector": "金融"},
    {"symbol": "002142", "name": "宁波银行", "industry": "银行", "sector": "金融"},
    {"symbol": "600919", "name": "江苏银行", "industry": "银行", "sector": "金融"},
    {"symbol": "601169", "name": "北京银行", "industry": "银行", "sector": "金融"},
    {"symbol": "002839", "name": "张家港行", "industry": "银行", "sector": "金融"},
    {"symbol": "600926", "name": "杭州银行", "industry": "银行", "sector": "金融"},
    {"symbol": "601318", "name": "中国平安", "industry": "保险", "sector": "金融"},
    {"symbol": "601628", "name": "中国人寿", "industry": "保险", "sector": "金融"},
    {"symbol": "601601", "name": "中国太保", "industry": "保险", "sector": "金融"},
    {"symbol": "002736", "name": "国信证券", "industry": "证券", "sector": "金融"},
    {"symbol": "600030", "name": "中信证券", "industry": "证券", "sector": "金融"},
    {"symbol": "601211", "name": "国泰君安", "industry": "证券", "sector": "金融"},
    {"symbol": "600837", "name": "海通证券", "industry": "证券", "sector": "金融"},
    {"symbol": "000776", "name": "广发证券", "industry": "证券", "sector": "金融"},
    {"symbol": "601688", "name": "华泰证券", "industry": "证券", "sector": "金融"},
    {"symbol": "600958", "name": "东方证券", "industry": "证券", "sector": "金融"},
    {"symbol": "300059", "name": "东方财富", "industry": "金融科技", "sector": "金融"},
    {"symbol": "300750", "name": "宁德时代", "industry": "电池", "sector": "新能源"},
    {"symbol": "002594", "name": "比亚迪", "industry": "新能源汽车", "sector": "新能源"},
    {"symbol": "601012", "name": "隆基绿能", "industry": "光伏", "sector": "新能源"},
    {"symbol": "600438", "name": "通威股份", "industry": "光伏", "sector": "新能源"},
    {"symbol": "002459", "name": "晶澳科技", "industry": "光伏", "sector": "新能源"},
    {"symbol": "688599", "name": "天合光能", "industry": "光伏", "sector": "新能源"},
    {"symbol": "300274", "name": "阳光电源", "industry": "逆变器", "sector": "新能源"},
    {"symbol": "002709", "name": "天赐材料", "industry": "电解液", "sector": "新能源"},
    {"symbol": "300014", "name": "亿纬锂能", "industry": "电池", "sector": "新能源"},
    {"symbol": "002812", "name": "恩捷股份", "industry": "隔膜", "sector": "新能源"},
    {"symbol": "300763", "name": "锦浪科技", "industry": "逆变器", "sector": "新能源"},
    {"symbol": "688390", "name": "固德威", "industry": "逆变器", "sector": "新能源"},
    {"symbol": "600276", "name": "恒瑞医药", "industry": "创新药", "sector": "医药"},
    {"symbol": "603259", "name": "药明康德", "industry": "CXO", "sector": "医药"},
    {"symbol": "300760", "name": "迈瑞医疗", "industry": "医疗器械", "sector": "医药"},
]

HK_STOCKS = [
    # ===== 科技/互联网 =====
    {"symbol": "00700", "name": "腾讯控股", "industry": "互联网", "sector": "科技"},
    {"symbol": "09988", "name": "阿里巴巴-W", "industry": "电商", "sector": "科技"},
    {"symbol": "09618", "name": "京东集团-SW", "industry": "电商", "sector": "科技"},
    {"symbol": "01810", "name": "小米集团-W", "industry": "消费电子", "sector": "科技"},
    {"symbol": "03690", "name": "美团-W", "industry": "本地生活", "sector": "科技"},
    {"symbol": "09888", "name": "百度集团-SW", "industry": "搜索引擎", "sector": "科技"},
    {"symbol": "09999", "name": "网易-S", "industry": "游戏", "sector": "科技"},
    {"symbol": "01024", "name": "快手-W", "industry": "短视频", "sector": "科技"},
    {"symbol": "02015", "name": "理想汽车-W", "industry": "新能源汽车", "sector": "科技"},
    {"symbol": "09868", "name": "小鹏汽车-W", "industry": "新能源汽车", "sector": "科技"},
    {"symbol": "09866", "name": "蔚来-SW", "industry": "新能源汽车", "sector": "科技"},
    {"symbol": "02518", "name": "汽车之家", "industry": "汽车资讯", "sector": "科技"},
    {"symbol": "06060", "name": "众安在线", "industry": "互联网保险", "sector": "科技"},
    {"symbol": "09626", "name": "哔哩哔哩-SW", "industry": "视频", "sector": "科技"},
    {"symbol": "01347", "name": "华虹半导体", "industry": "晶圆代工", "sector": "科技"},
    {"symbol": "00981", "name": "中芯国际", "industry": "晶圆代工", "sector": "科技"},
    {"symbol": "02382", "name": "舜宇光学科技", "industry": "光学", "sector": "科技"},
    {"symbol": "00285", "name": "比亚迪电子", "industry": "电子制造", "sector": "科技"},
    {"symbol": "01211", "name": "比亚迪股份", "industry": "新能源汽车", "sector": "科技"},
    {"symbol": "02269", "name": "药明生物", "industry": "CXO", "sector": "医药"},

    # ===== 金融 =====
    {"symbol": "02318", "name": "中国平安H", "industry": "保险", "sector": "金融"},
    {"symbol": "01299", "name": "友邦保险", "industry": "保险", "sector": "金融"},
    {"symbol": "00388", "name": "香港交易所", "industry": "交易所", "sector": "金融"},
    {"symbol": "03968", "name": "招商银行H", "industry": "银行", "sector": "金融"},
    {"symbol": "01398", "name": "工商银行H", "industry": "银行", "sector": "金融"},
    {"symbol": "00939", "name": "建设银行H", "industry": "银行", "sector": "金融"},
    {"symbol": "01288", "name": "农业银行H", "industry": "银行", "sector": "金融"},
    {"symbol": "03988", "name": "中国银行H", "industry": "银行", "sector": "金融"},
    {"symbol": "06881", "name": "中信证券H", "industry": "证券", "sector": "金融"},
    {"symbol": "02628", "name": "中国人寿H", "industry": "保险", "sector": "金融"},
    {"symbol": "02601", "name": "中国太保H", "industry": "保险", "sector": "金融"},
    {"symbol": "01658", "name": "邮储银行H", "industry": "银行", "sector": "金融"},
    {"symbol": "06837", "name": "海通证券H", "industry": "证券", "sector": "金融"},

    # ===== 消费 =====
    {"symbol": "02020", "name": "安踏体育", "industry": "运动服饰", "sector": "消费"},
    {"symbol": "09633", "name": "农夫山泉", "industry": "饮料", "sector": "消费"},
    {"symbol": "00027", "name": "银河娱乐", "industry": "博彩", "sector": "消费"},
    {"symbol": "01928", "name": "金沙中国有限公司", "industry": "博彩", "sector": "消费"},
    {"symbol": "02331", "name": "李宁", "industry": "运动服饰", "sector": "消费"},
    {"symbol": "06160", "name": "百济神州", "industry": "创新药", "sector": "医药"},
    {"symbol": "01177", "name": "中国生物制药", "industry": "制药", "sector": "医药"},
    {"symbol": "02319", "name": "蒙牛乳业", "industry": "乳制品", "sector": "消费"},
    {"symbol": "00291", "name": "华润啤酒", "industry": "啤酒", "sector": "消费"},
    {"symbol": "01044", "name": "恒安国际", "industry": "日用品", "sector": "消费"},
    {"symbol": "06862", "name": "海底捞", "industry": "餐饮", "sector": "消费"},
    {"symbol": "09961", "name": "携程集团-S", "industry": "旅游", "sector": "消费"},
    {"symbol": "09901", "name": "新东方在线", "industry": "教育", "sector": "消费"},
    {"symbol": "01405", "name": "达势股份", "industry": "餐饮", "sector": "消费"},
    {"symbol": "02150", "name": "奈雪的茶", "industry": "茶饮", "sector": "消费"},
    {"symbol": "06969", "name": "思摩尔国际", "industry": "电子烟", "sector": "消费"},

    # ===== 医药 =====
    {"symbol": "02269", "name": "药明生物", "industry": "CXO", "sector": "医药"},
    {"symbol": "01093", "name": "石药集团", "industry": "制药", "sector": "医药"},
    {"symbol": "06160", "name": "百济神州", "industry": "创新药", "sector": "医药"},
    {"symbol": "02196", "name": "复星医药H", "industry": "综合药企", "sector": "医药"},
    {"symbol": "01177", "name": "中国生物制药", "industry": "制药", "sector": "医药"},
    {"symbol": "06185", "name": "康希诺生物", "industry": "疫苗", "sector": "医药"},
    {"symbol": "02359", "name": "药明康德H", "industry": "CXO", "sector": "医药"},

    # ===== 汽车/新能源 =====
    {"symbol": "01211", "name": "比亚迪股份", "industry": "新能源汽车", "sector": "新能源"},
    {"symbol": "02015", "name": "理想汽车-W", "industry": "新能源汽车", "sector": "新能源"},
    {"symbol": "09868", "name": "小鹏汽车-W", "industry": "新能源汽车", "sector": "新能源"},
    {"symbol": "09866", "name": "蔚来-SW", "industry": "新能源汽车", "sector": "新能源"},
    {"symbol": "02333", "name": "长城汽车", "industry": "汽车", "sector": "工业"},
    {"symbol": "00175", "name": "吉利汽车", "industry": "汽车", "sector": "工业"},
    {"symbol": "01958", "name": "北京汽车", "industry": "汽车", "sector": "工业"},
    {"symbol": "02238", "name": "广汽集团H", "industry": "汽车", "sector": "工业"},

    # ===== 能源/资源 =====
    {"symbol": "00883", "name": "中国海洋石油", "industry": "石油", "sector": "能源"},
    {"symbol": "00857", "name": "中国石油股份", "industry": "石油", "sector": "能源"},
    {"symbol": "00386", "name": "中国石油化工", "industry": "石化", "sector": "能源"},
    {"symbol": "01088", "name": "中国神华", "industry": "煤炭", "sector": "能源"},
    {"symbol": "03323", "name": "中国建材", "industry": "建材", "sector": "工业"},
    {"symbol": "00914", "name": "海螺水泥H", "industry": "水泥", "sector": "工业"},
    {"symbol": "02600", "name": "中国铝业", "industry": "铝", "sector": "工业"},
    {"symbol": "03311", "name": "中国建筑国际", "industry": "建筑", "sector": "工业"},
    {"symbol": "01133", "name": "哈尔滨电气", "industry": "电力设备", "sector": "工业"},

    # ===== 电信 =====
    {"symbol": "00941", "name": "中国移动", "industry": "运营商", "sector": "科技"},
    {"symbol": "00728", "name": "中国电信", "industry": "运营商", "sector": "科技"},
    {"symbol": "00762", "name": "中国联通", "industry": "运营商", "sector": "科技"},

    # ===== 地产/基建 =====
    {"symbol": "02007", "name": "碧桂园", "industry": "房地产", "sector": "地产"},
    {"symbol": "03333", "name": "中国恒大", "industry": "房地产", "sector": "地产"},
    {"symbol": "01109", "name": "华润置地", "industry": "房地产", "sector": "地产"},
    {"symbol": "00688", "name": "中国海外发展", "industry": "房地产", "sector": "地产"},
    {"symbol": "00017", "name": "新世界发展", "industry": "房地产", "sector": "地产"},
    {"symbol": "00012", "name": "恒基地产", "industry": "房地产", "sector": "地产"},
    {"symbol": "00016", "name": "新鸿基地产", "industry": "房地产", "sector": "地产"},
    {"symbol": "00001", "name": "长和", "industry": "综合", "sector": "综合"},
    {"symbol": "00002", "name": "中电控股", "industry": "电力", "sector": "公用事业"},
    {"symbol": "00003", "name": "香港中华煤气", "industry": "燃气", "sector": "公用事业"},
    {"symbol": "00005", "name": "汇丰控股", "industry": "银行", "sector": "金融"},
    {"symbol": "00006", "name": "电能实业", "industry": "电力", "sector": "公用事业"},
    {"symbol": "00011", "name": "恒生银行", "industry": "银行", "sector": "金融"},
    {"symbol": "00020", "name": "商汤-W", "industry": "AI", "sector": "科技"},
    {"symbol": "02013", "name": "微盟集团", "industry": "SaaS", "sector": "科技"},
    {"symbol": "09999", "name": "网易-S", "industry": "游戏", "sector": "科技"},
    {"symbol": "00267", "name": "中信股份", "industry": "综合", "sector": "综合"},
    {"symbol": "00288", "name": "万洲国际", "industry": "肉制品", "sector": "消费"},
    {"symbol": "01177", "name": "中国生物制药", "industry": "制药", "sector": "医药"},
    {"symbol": "01548", "name": "金斯瑞生物科技", "industry": "生物科技", "sector": "医药"},
    {"symbol": "06185", "name": "康希诺生物", "industry": "疫苗", "sector": "医药"},
    {"symbol": "02162", "name": "康诺亚-B", "industry": "创新药", "sector": "医药"},
    {"symbol": "09995", "name": "荣昌生物", "industry": "创新药", "sector": "医药"},
    {"symbol": "01801", "name": "信达生物", "industry": "创新药", "sector": "医药"},
    {"symbol": "09926", "name": "康方生物", "industry": "创新药", "sector": "医药"},
    {"symbol": "02126", "name": "药师帮", "industry": "医药电商", "sector": "医药"},
    {"symbol": "06618", "name": "京东健康", "industry": "医疗健康", "sector": "医药"},
    {"symbol": "00241", "name": "阿里健康", "industry": "医疗健康", "sector": "医药"},
    {"symbol": "02400", "name": "心动公司", "industry": "游戏", "sector": "科技"},
    {"symbol": "00772", "name": "阅文集团", "industry": "网文", "sector": "科技"},
    {"symbol": "09698", "name": "万国数据-SW", "industry": "IDC", "sector": "科技"},
    {"symbol": "09626", "name": "哔哩哔哩-SW", "industry": "视频", "sector": "科技"},
    {"symbol": "02013", "name": "微盟集团", "industry": "SaaS", "sector": "科技"},
    {"symbol": "09961", "name": "携程集团-S", "industry": "旅游", "sector": "消费"},
    {"symbol": "09901", "name": "新东方在线", "industry": "教育", "sector": "消费"},
    {"symbol": "01797", "name": "新东方-S", "industry": "教育", "sector": "消费"},
    {"symbol": "06969", "name": "思摩尔国际", "industry": "电子烟", "sector": "消费"},
    {"symbol": "09923", "name": "移卡", "industry": "支付", "sector": "金融"},

    # ===== 补充港股标的（凑满 200+） =====
    {"symbol": "00001", "name": "长和", "industry": "综合", "sector": "综合"},
    {"symbol": "00002", "name": "中电控股", "industry": "电力", "sector": "公用事业"},
    {"symbol": "00003", "name": "香港中华煤气", "industry": "燃气", "sector": "公用事业"},
    {"symbol": "00005", "name": "汇丰控股", "industry": "银行", "sector": "金融"},
    {"symbol": "00006", "name": "电能实业", "industry": "电力", "sector": "公用事业"},
    {"symbol": "00011", "name": "恒生银行", "industry": "银行", "sector": "金融"},
    {"symbol": "00012", "name": "恒基地产", "industry": "房地产", "sector": "地产"},
    {"symbol": "00016", "name": "新鸿基地产", "industry": "房地产", "sector": "地产"},
    {"symbol": "00017", "name": "新世界发展", "industry": "房地产", "sector": "地产"},
    {"symbol": "00020", "name": "商汤-W", "industry": "AI", "sector": "科技"},
    {"symbol": "00027", "name": "银河娱乐", "industry": "博彩", "sector": "消费"},
    {"symbol": "00267", "name": "中信股份", "industry": "综合", "sector": "综合"},
    {"symbol": "00288", "name": "万洲国际", "industry": "肉制品", "sector": "消费"},
    {"symbol": "00386", "name": "中国石油化工", "industry": "石化", "sector": "能源"},
    {"symbol": "00388", "name": "香港交易所", "industry": "交易所", "sector": "金融"},
    {"symbol": "00688", "name": "中国海外发展", "industry": "房地产", "sector": "地产"},
    {"symbol": "00728", "name": "中国电信", "industry": "运营商", "sector": "科技"},
    {"symbol": "00762", "name": "中国联通", "industry": "运营商", "sector": "科技"},
    {"symbol": "00772", "name": "阅文集团", "industry": "网文", "sector": "科技"},
    {"symbol": "00857", "name": "中国石油股份", "industry": "石油", "sector": "能源"},
    {"symbol": "00883", "name": "中国海洋石油", "industry": "石油", "sector": "能源"},
    {"symbol": "00914", "name": "海螺水泥H", "industry": "水泥", "sector": "工业"},
    {"symbol": "00939", "name": "建设银行H", "industry": "银行", "sector": "金融"},
    {"symbol": "00941", "name": "中国移动", "industry": "运营商", "sector": "科技"},
    {"symbol": "00981", "name": "中芯国际", "industry": "晶圆代工", "sector": "科技"},
    {"symbol": "01044", "name": "恒安国际", "industry": "日用品", "sector": "消费"},
    {"symbol": "01088", "name": "中国神华", "industry": "煤炭", "sector": "能源"},
    {"symbol": "01093", "name": "石药集团", "industry": "制药", "sector": "医药"},
    {"symbol": "01109", "name": "华润置地", "industry": "房地产", "sector": "地产"},
    {"symbol": "01133", "name": "哈尔滨电气", "industry": "电力设备", "sector": "工业"},
    {"symbol": "01177", "name": "中国生物制药", "industry": "制药", "sector": "医药"},
    {"symbol": "01211", "name": "比亚迪股份", "industry": "新能源汽车", "sector": "新能源"},
    {"symbol": "01288", "name": "农业银行H", "industry": "银行", "sector": "金融"},
    {"symbol": "01299", "name": "友邦保险", "industry": "保险", "sector": "金融"},
    {"symbol": "01347", "name": "华虹半导体", "industry": "晶圆代工", "sector": "科技"},
    {"symbol": "01398", "name": "工商银行H", "industry": "银行", "sector": "金融"},
    {"symbol": "01405", "name": "达势股份", "industry": "餐饮", "sector": "消费"},
    {"symbol": "01548", "name": "金斯瑞生物科技", "industry": "生物科技", "sector": "医药"},
    {"symbol": "01658", "name": "邮储银行H", "industry": "银行", "sector": "金融"},
    {"symbol": "01801", "name": "信达生物", "industry": "创新药", "sector": "医药"},
    {"symbol": "01928", "name": "金沙中国有限公司", "industry": "博彩", "sector": "消费"},
    {"symbol": "01958", "name": "北京汽车", "industry": "汽车", "sector": "工业"},
    {"symbol": "02007", "name": "碧桂园", "industry": "房地产", "sector": "地产"},
    {"symbol": "02020", "name": "安踏体育", "industry": "运动服饰", "sector": "消费"},
    {"symbol": "02126", "name": "药师帮", "industry": "医药电商", "sector": "医药"},
    {"symbol": "02150", "name": "奈雪的茶", "industry": "茶饮", "sector": "消费"},
    {"symbol": "02162", "name": "康诺亚-B", "industry": "创新药", "sector": "医药"},
    {"symbol": "02196", "name": "复星医药H", "industry": "综合药企", "sector": "医药"},
    {"symbol": "02238", "name": "广汽集团H", "industry": "汽车", "sector": "工业"},
    {"symbol": "02269", "name": "药明生物", "industry": "CXO", "sector": "医药"},
    {"symbol": "02318", "name": "中国平安H", "industry": "保险", "sector": "金融"},
    {"symbol": "02319", "name": "蒙牛乳业", "industry": "乳制品", "sector": "消费"},
    {"symbol": "02331", "name": "李宁", "industry": "运动服饰", "sector": "消费"},
    {"symbol": "02333", "name": "长城汽车", "industry": "汽车", "sector": "工业"},
    {"symbol": "02359", "name": "药明康德H", "industry": "CXO", "sector": "医药"},
    {"symbol": "02382", "name": "舜宇光学科技", "industry": "光学", "sector": "科技"},
    {"symbol": "02400", "name": "心动公司", "industry": "游戏", "sector": "科技"},
    {"symbol": "02600", "name": "中国铝业", "industry": "铝", "sector": "工业"},
    {"symbol": "02601", "name": "中国太保H", "industry": "保险", "sector": "金融"},
    {"symbol": "02628", "name": "中国人寿H", "industry": "保险", "sector": "金融"},
    {"symbol": "03311", "name": "中国建筑国际", "industry": "建筑", "sector": "工业"},
    {"symbol": "03323", "name": "中国建材", "industry": "建材", "sector": "工业"},
    {"symbol": "03333", "name": "中国恒大", "industry": "房地产", "sector": "地产"},
    {"symbol": "03968", "name": "招商银行H", "industry": "银行", "sector": "金融"},
    {"symbol": "03988", "name": "中国银行H", "industry": "银行", "sector": "金融"},
    {"symbol": "06060", "name": "众安在线", "industry": "互联网保险", "sector": "金融"},
    {"symbol": "06160", "name": "百济神州", "industry": "创新药", "sector": "医药"},
    {"symbol": "06185", "name": "康希诺生物", "industry": "疫苗", "sector": "医药"},
    {"symbol": "06618", "name": "京东健康", "industry": "医疗健康", "sector": "医药"},
    {"symbol": "06837", "name": "海通证券H", "industry": "证券", "sector": "金融"},
    {"symbol": "06862", "name": "海底捞", "industry": "餐饮", "sector": "消费"},
    {"symbol": "06881", "name": "中信证券H", "industry": "证券", "sector": "金融"},
    {"symbol": "09626", "name": "哔哩哔哩-SW", "industry": "视频", "sector": "科技"},
    {"symbol": "09633", "name": "农夫山泉", "industry": "饮料", "sector": "消费"},
    {"symbol": "09698", "name": "万国数据-SW", "industry": "IDC", "sector": "科技"},
    {"symbol": "09926", "name": "康方生物", "industry": "创新药", "sector": "医药"},
    {"symbol": "09955", "name": "智云健康", "industry": "医疗SaaS", "sector": "医药"},
    {"symbol": "09969", "name": "诺诚健华", "industry": "创新药", "sector": "医药"},
    {"symbol": "09979", "name": "绿城管理控股", "industry": "代建", "sector": "地产"},
    {"symbol": "09988", "name": "阿里巴巴-W", "industry": "电商", "sector": "科技"},
    {"symbol": "09995", "name": "荣昌生物", "industry": "创新药", "sector": "医药"},
    {"symbol": "09999", "name": "网易-S", "industry": "游戏", "sector": "科技"},
    {"symbol": "01024", "name": "快手-W", "industry": "短视频", "sector": "科技"},
    {"symbol": "02015", "name": "理想汽车-W", "industry": "新能源汽车", "sector": "新能源"},
    {"symbol": "09868", "name": "小鹏汽车-W", "industry": "新能源汽车", "sector": "新能源"},
    {"symbol": "09866", "name": "蔚来-SW", "industry": "新能源汽车", "sector": "新能源"},
    {"symbol": "09888", "name": "百度集团-SW", "industry": "搜索引擎", "sector": "科技"},
    {"symbol": "01810", "name": "小米集团-W", "industry": "消费电子", "sector": "科技"},
    {"symbol": "03690", "name": "美团-W", "industry": "本地生活", "sector": "科技"},
    {"symbol": "09618", "name": "京东集团-SW", "industry": "电商", "sector": "科技"},
    {"symbol": "00700", "name": "腾讯控股", "industry": "互联网", "sector": "科技"},

    # ===== 港股补充（更多行业覆盖） =====
    {"symbol": "00285", "name": "比亚迪电子", "industry": "电子制造", "sector": "科技"},
    {"symbol": "00291", "name": "华润啤酒", "industry": "啤酒", "sector": "消费"},
    {"symbol": "00388", "name": "香港交易所", "industry": "交易所", "sector": "金融"},
    {"symbol": "00493", "name": "国美零售", "industry": "零售", "sector": "消费"},
    {"symbol": "00656", "name": "复星国际", "industry": "综合", "sector": "综合"},
    {"symbol": "00669", "name": "创科实业", "industry": "电动工具", "sector": "工业"},
    {"symbol": "00823", "name": "领展房产基金", "industry": "REITs", "sector": "地产"},
    {"symbol": "00857", "name": "中国石油股份", "industry": "石油", "sector": "能源"},
    {"symbol": "00868", "name": "信义玻璃", "industry": "玻璃", "sector": "工业"},
    {"symbol": "00960", "name": "龙湖集团", "industry": "房地产", "sector": "地产"},
    {"symbol": "00966", "name": "中国太平", "industry": "保险", "sector": "金融"},
    {"symbol": "00992", "name": "联想集团", "industry": "PC", "sector": "科技"},
    {"symbol": "01038", "name": "长江基建集团", "industry": "基建", "sector": "工业"},
    {"symbol": "01068", "name": "雨润食品", "industry": "肉制品", "sector": "消费"},
    {"symbol": "01093", "name": "石药集团", "industry": "制药", "sector": "医药"},
    {"symbol": "01113", "name": "长实集团", "industry": "房地产", "sector": "地产"},
    {"symbol": "01171", "name": "兖矿能源", "industry": "煤炭", "sector": "能源"},
    {"symbol": "01208", "name": "五矿资源", "industry": "矿业", "sector": "工业"},
    {"symbol": "01288", "name": "农业银行H", "industry": "银行", "sector": "金融"},
    {"symbol": "01308", "name": "海丰国际", "industry": "航运", "sector": "交运"},
    {"symbol": "01313", "name": "华润水泥控股", "industry": "水泥", "sector": "工业"},
    {"symbol": "01316", "name": "耐世特汽车", "industry": "汽车零部件", "sector": "工业"},
    {"symbol": "01336", "name": "新华保险", "industry": "保险", "sector": "金融"},
    {"symbol": "01339", "name": "中国人民保险集团", "industry": "保险", "sector": "金融"},
    {"symbol": "01347", "name": "华虹半导体", "industry": "晶圆代工", "sector": "科技"},
    {"symbol": "01359", "name": "中国信达", "industry": "资产管理", "sector": "金融"},
    {"symbol": "01368", "name": "特步国际", "industry": "运动服饰", "sector": "消费"},
    {"symbol": "01378", "name": "中国宏桥", "industry": "铝", "sector": "工业"},
    {"symbol": "01382", "name": "互太纺织", "industry": "纺织", "sector": "工业"},
    {"symbol": "01398", "name": "工商银行H", "industry": "银行", "sector": "金融"},
    {"symbol": "01448", "name": "福寿园", "industry": "殡葬", "sector": "消费"},
    {"symbol": "01458", "name": "周黑鸭", "industry": "卤制品", "sector": "消费"},
    {"symbol": "01478", "name": "丘钛科技", "industry": "摄像头模组", "sector": "科技"},
    {"symbol": "01548", "name": "金斯瑞生物科技", "industry": "生物科技", "sector": "医药"},
    {"symbol": "01579", "name": "颐海国际", "industry": "调味品", "sector": "消费"},
    {"symbol": "01585", "name": "雅迪控股", "industry": "电动车", "sector": "消费"},
    {"symbol": "01638", "name": "佳兆业集团", "industry": "房地产", "sector": "地产"},
    {"symbol": "01658", "name": "邮储银行H", "industry": "银行", "sector": "金融"},
    {"symbol": "01691", "name": "JS环球生活", "industry": "小家电", "sector": "消费"},
    {"symbol": "01728", "name": "中国电信", "industry": "运营商", "sector": "科技"},
    {"symbol": "01766", "name": "中国中车H", "industry": "轨交", "sector": "工业"},
    {"symbol": "01772", "name": "赣锋锂业H", "industry": "锂", "sector": "新能源"},
    {"symbol": "01776", "name": "广发证券H", "industry": "证券", "sector": "金融"},
    {"symbol": "01787", "name": "山东黄金H", "industry": "黄金", "sector": "工业"},
    {"symbol": "01812", "name": "晨鸣纸业H", "industry": "造纸", "sector": "工业"},
    {"symbol": "01816", "name": "中广核电力", "industry": "核电", "sector": "公用事业"},
    {"symbol": "01818", "name": "招金矿业", "industry": "黄金", "sector": "工业"},
    {"symbol": "01839", "name": "中集车辆", "industry": "车辆", "sector": "工业"},
    {"symbol": "01876", "name": "百威亚太", "industry": "啤酒", "sector": "消费"},
    {"symbol": "01898", "name": "中煤能源", "industry": "煤炭", "sector": "能源"},
    {"symbol": "01919", "name": "中远海控", "industry": "航运", "sector": "交运"},
    {"symbol": "01929", "name": "周大福", "industry": "珠宝", "sector": "消费"},
    {"symbol": "01951", "name": "锦欣生殖", "industry": "医疗服务", "sector": "医药"},
    {"symbol": "01997", "name": "九龙仓置业", "industry": "房地产", "sector": "地产"},
    {"symbol": "01999", "name": "敏华控股", "industry": "家具", "sector": "消费"},
    {"symbol": "02007", "name": "碧桂园", "industry": "房地产", "sector": "地产"},
    {"symbol": "02013", "name": "微盟集团", "industry": "SaaS", "sector": "科技"},
    {"symbol": "02018", "name": "瑞声科技", "industry": "声学", "sector": "科技"},
    {"symbol": "02020", "name": "安踏体育", "industry": "运动服饰", "sector": "消费"},
    {"symbol": "02038", "name": "富智康集团", "industry": "电子制造", "sector": "科技"},
    {"symbol": "02057", "name": "中通快递-SW", "industry": "快递", "sector": "交运"},
    {"symbol": "02068", "name": "中铝国际", "industry": "工程", "sector": "工业"},
    {"symbol": "02099", "name": "中国黄金国际", "industry": "黄金", "sector": "工业"},
    {"symbol": "02120", "name": "康宁医院", "industry": "医院", "sector": "医药"},
    {"symbol": "02128", "name": "中国联塑", "industry": "建材", "sector": "工业"},
    {"symbol": "02162", "name": "康诺亚-B", "industry": "创新药", "sector": "医药"},
    {"symbol": "02196", "name": "复星医药H", "industry": "综合药企", "sector": "医药"},
    {"symbol": "02202", "name": "万科企业H", "industry": "房地产", "sector": "地产"},
    {"symbol": "02208", "name": "金风科技H", "industry": "风电", "sector": "新能源"},
    {"symbol": "02238", "name": "广汽集团H", "industry": "汽车", "sector": "工业"},
    {"symbol": "02269", "name": "药明生物", "industry": "CXO", "sector": "医药"},
    {"symbol": "02282", "name": "美高梅中国", "industry": "博彩", "sector": "消费"},
    {"symbol": "02313", "name": "申洲国际", "industry": "纺织代工", "sector": "工业"},
    {"symbol": "02318", "name": "中国平安H", "industry": "保险", "sector": "金融"},
    {"symbol": "02319", "name": "蒙牛乳业", "industry": "乳制品", "sector": "消费"},
    {"symbol": "02328", "name": "中国财险", "industry": "保险", "sector": "金融"},
    {"symbol": "02331", "name": "李宁", "industry": "运动服饰", "sector": "消费"},
    {"symbol": "02333", "name": "长城汽车", "industry": "汽车", "sector": "工业"},
    {"symbol": "02357", "name": "中航科工", "industry": "军工", "sector": "军工"},
    {"symbol": "02380", "name": "中国电力", "industry": "电力", "sector": "公用事业"},
    {"symbol": "02382", "name": "舜宇光学科技", "industry": "光学", "sector": "科技"},
    {"symbol": "02386", "name": "中石化炼化工程", "industry": "工程", "sector": "工业"},
    {"symbol": "02388", "name": "中银香港", "industry": "银行", "sector": "金融"},
    {"symbol": "02600", "name": "中国铝业", "industry": "铝", "sector": "工业"},
    {"symbol": "02601", "name": "中国太保H", "industry": "保险", "sector": "金融"},
    {"symbol": "02607", "name": "上海医药H", "industry": "医药流通", "sector": "医药"},
    {"symbol": "02611", "name": "国泰君安H", "industry": "证券", "sector": "金融"},
    {"symbol": "02628", "name": "中国人寿H", "industry": "保险", "sector": "金融"},
    {"symbol": "02638", "name": "港灯-SS", "industry": "电力", "sector": "公用事业"},
    {"symbol": "02669", "name": "中海物业", "industry": "物业", "sector": "地产"},
    {"symbol": "02688", "name": "新奥能源", "industry": "燃气", "sector": "公用事业"},
    {"symbol": "02799", "name": "中国华融", "industry": "资产管理", "sector": "金融"},
    {"symbol": "02899", "name": "紫金矿业H", "industry": "黄金", "sector": "工业"},
    {"symbol": "03311", "name": "中国建筑国际", "industry": "建筑", "sector": "工业"},
    {"symbol": "03320", "name": "华润医药", "industry": "医药流通", "sector": "医药"},
    {"symbol": "03323", "name": "中国建材", "industry": "建材", "sector": "工业"},
    {"symbol": "03328", "name": "交通银行", "industry": "银行", "sector": "金融"},
    {"symbol": "03331", "name": "维达国际", "industry": "纸品", "sector": "消费"},
    {"symbol": "03333", "name": "中国恒大", "industry": "房地产", "sector": "地产"},
    {"symbol": "03360", "name": "远东宏信", "industry": "融资租赁", "sector": "金融"},
    {"symbol": "03383", "name": "雅居乐集团", "industry": "房地产", "sector": "地产"},
    {"symbol": "03692", "name": "翰森制药", "industry": "制药", "sector": "医药"},
    {"symbol": "03759", "name": "康龙化成H", "industry": "CRO", "sector": "医药"},
    {"symbol": "03799", "name": "达利食品", "industry": "食品", "sector": "消费"},
    {"symbol": "03888", "name": "金山软件", "industry": "软件", "sector": "科技"},
    {"symbol": "03968", "name": "招商银行H", "industry": "银行", "sector": "金融"},
    {"symbol": "03988", "name": "中国银行H", "industry": "银行", "sector": "金融"},
    {"symbol": "03993", "name": "洛阳钼业H", "industry": "矿业", "sector": "工业"},
    {"symbol": "06030", "name": "中信证券", "industry": "证券", "sector": "金融"},
    {"symbol": "06060", "name": "众安在线", "industry": "互联网保险", "sector": "金融"},
    {"symbol": "06098", "name": "碧桂园服务", "industry": "物业", "sector": "地产"},
    {"symbol": "06160", "name": "百济神州", "industry": "创新药", "sector": "医药"},
    {"symbol": "06185", "name": "康希诺生物", "industry": "疫苗", "sector": "医药"},
    {"symbol": "06186", "name": "中国飞鹤", "industry": "奶粉", "sector": "消费"},
    {"symbol": "06618", "name": "京东健康", "industry": "医疗健康", "sector": "医药"},
    {"symbol": "06690", "name": "海尔智家H", "industry": "家电", "sector": "消费"},
    {"symbol": "06818", "name": "中国光大银行H", "industry": "银行", "sector": "金融"},
    {"symbol": "06837", "name": "海通证券H", "industry": "证券", "sector": "金融"},
    {"symbol": "06862", "name": "海底捞", "industry": "餐饮", "sector": "消费"},
    {"symbol": "06865", "name": "福莱特玻璃", "industry": "光伏玻璃", "sector": "新能源"},
    {"symbol": "06881", "name": "中信证券H", "industry": "证券", "sector": "金融"},
    {"symbol": "06969", "name": "思摩尔国际", "industry": "电子烟", "sector": "消费"},
    {"symbol": "09626", "name": "哔哩哔哩-SW", "industry": "视频", "sector": "科技"},
    {"symbol": "09633", "name": "农夫山泉", "industry": "饮料", "sector": "消费"},
    {"symbol": "09698", "name": "万国数据-SW", "industry": "IDC", "sector": "科技"},
    {"symbol": "09868", "name": "小鹏汽车-W", "industry": "新能源汽车", "sector": "新能源"},
    {"symbol": "09866", "name": "蔚来-SW", "industry": "新能源汽车", "sector": "新能源"},
    {"symbol": "09901", "name": "新东方在线", "industry": "教育", "sector": "消费"},
    {"symbol": "09909", "name": "宝尊电商", "industry": "电商代运营", "sector": "科技"},
    {"symbol": "09922", "name": "九毛九", "industry": "餐饮", "sector": "消费"},
    {"symbol": "09926", "name": "康方生物", "industry": "创新药", "sector": "医药"},
    {"symbol": "09961", "name": "携程集团-S", "industry": "旅游", "sector": "消费"},
    {"symbol": "09969", "name": "诺诚健华", "industry": "创新药", "sector": "医药"},
    {"symbol": "09979", "name": "绿城管理控股", "industry": "代建", "sector": "地产"},
    {"symbol": "09988", "name": "阿里巴巴-W", "industry": "电商", "sector": "科技"},
    {"symbol": "09992", "name": "泡泡玛特", "industry": "潮玩", "sector": "消费"},
    {"symbol": "09995", "name": "荣昌生物", "industry": "创新药", "sector": "医药"},
    {"symbol": "09999", "name": "网易-S", "industry": "游戏", "sector": "科技"},

    # ===== 更多港股（凑满 250+） =====
    {"symbol": "00001", "name": "长和", "industry": "综合", "sector": "综合"},
    {"symbol": "00002", "name": "中电控股", "industry": "电力", "sector": "公用事业"},
    {"symbol": "00003", "name": "香港中华煤气", "industry": "燃气", "sector": "公用事业"},
    {"symbol": "00005", "name": "汇丰控股", "industry": "银行", "sector": "金融"},
    {"symbol": "00006", "name": "电能实业", "industry": "电力", "sector": "公用事业"},
    {"symbol": "00011", "name": "恒生银行", "industry": "银行", "sector": "金融"},
    {"symbol": "00012", "name": "恒基地产", "industry": "房地产", "sector": "地产"},
    {"symbol": "00016", "name": "新鸿基地产", "industry": "房地产", "sector": "地产"},
    {"symbol": "00017", "name": "新世界发展", "industry": "房地产", "sector": "地产"},
    {"symbol": "00020", "name": "商汤-W", "industry": "AI", "sector": "科技"},
    {"symbol": "00027", "name": "银河娱乐", "industry": "博彩", "sector": "消费"},
    {"symbol": "00267", "name": "中信股份", "industry": "综合", "sector": "综合"},
    {"symbol": "00288", "name": "万洲国际", "industry": "肉制品", "sector": "消费"},
    {"symbol": "00386", "name": "中国石油化工", "industry": "石化", "sector": "能源"},
    {"symbol": "00388", "name": "香港交易所", "industry": "交易所", "sector": "金融"},
    {"symbol": "00688", "name": "中国海外发展", "industry": "房地产", "sector": "地产"},
    {"symbol": "00728", "name": "中国电信", "industry": "运营商", "sector": "科技"},
    {"symbol": "00762", "name": "中国联通", "industry": "运营商", "sector": "科技"},
    {"symbol": "00857", "name": "中国石油股份", "industry": "石油", "sector": "能源"},
    {"symbol": "00883", "name": "中国海洋石油", "industry": "石油", "sector": "能源"},
    {"symbol": "00939", "name": "建设银行H", "industry": "银行", "sector": "金融"},
    {"symbol": "00941", "name": "中国移动", "industry": "运营商", "sector": "科技"},
    {"symbol": "00981", "name": "中芯国际", "industry": "晶圆代工", "sector": "科技"},
    {"symbol": "01038", "name": "长江基建集团", "industry": "基建", "sector": "工业"},
    {"symbol": "01088", "name": "中国神华", "industry": "煤炭", "sector": "能源"},
    {"symbol": "01093", "name": "石药集团", "industry": "制药", "sector": "医药"},
    {"symbol": "01109", "name": "华润置地", "industry": "房地产", "sector": "地产"},
    {"symbol": "01177", "name": "中国生物制药", "industry": "制药", "sector": "医药"},
    {"symbol": "01211", "name": "比亚迪股份", "industry": "新能源汽车", "sector": "新能源"},
    {"symbol": "01288", "name": "农业银行H", "industry": "银行", "sector": "金融"},
    {"symbol": "01299", "name": "友邦保险", "industry": "保险", "sector": "金融"},
    {"symbol": "01336", "name": "新华保险", "industry": "保险", "sector": "金融"},
    {"symbol": "01339", "name": "中国人民保险集团", "industry": "保险", "sector": "金融"},
    {"symbol": "01347", "name": "华虹半导体", "industry": "晶圆代工", "sector": "科技"},
    {"symbol": "01359", "name": "中国信达", "industry": "资产管理", "sector": "金融"},
    {"symbol": "01368", "name": "特步国际", "industry": "运动服饰", "sector": "消费"},
    {"symbol": "01378", "name": "中国宏桥", "industry": "铝", "sector": "工业"},
    {"symbol": "01398", "name": "工商银行H", "industry": "银行", "sector": "金融"},
    {"symbol": "01458", "name": "周黑鸭", "industry": "卤制品", "sector": "消费"},
    {"symbol": "01548", "name": "金斯瑞生物科技", "industry": "生物科技", "sector": "医药"},
    {"symbol": "01579", "name": "颐海国际", "industry": "调味品", "sector": "消费"},
    {"symbol": "01585", "name": "雅迪控股", "industry": "电动车", "sector": "消费"},
    {"symbol": "01658", "name": "邮储银行H", "industry": "银行", "sector": "金融"},
    {"symbol": "01772", "name": "赣锋锂业H", "industry": "锂", "sector": "新能源"},
    {"symbol": "01776", "name": "广发证券H", "industry": "证券", "sector": "金融"},
    {"symbol": "01816", "name": "中广核电力", "industry": "核电", "sector": "公用事业"},
    {"symbol": "01876", "name": "百威亚太", "industry": "啤酒", "sector": "消费"},
    {"symbol": "01898", "name": "中煤能源", "industry": "煤炭", "sector": "能源"},
    {"symbol": "01919", "name": "中远海控", "industry": "航运", "sector": "交运"},
    {"symbol": "01928", "name": "金沙中国有限公司", "industry": "博彩", "sector": "消费"},
    {"symbol": "01929", "name": "周大福", "industry": "珠宝", "sector": "消费"},
    {"symbol": "01999", "name": "敏华控股", "industry": "家具", "sector": "消费"},
    {"symbol": "02007", "name": "碧桂园", "industry": "房地产", "sector": "地产"},
    {"symbol": "02018", "name": "瑞声科技", "industry": "声学", "sector": "科技"},
    {"symbol": "02020", "name": "安踏体育", "industry": "运动服饰", "sector": "消费"},
    {"symbol": "02057", "name": "中通快递-SW", "industry": "快递", "sector": "交运"},
    {"symbol": "02128", "name": "中国联塑", "industry": "建材", "sector": "工业"},
    {"symbol": "02202", "name": "万科企业H", "industry": "房地产", "sector": "地产"},
    {"symbol": "02269", "name": "药明生物", "industry": "CXO", "sector": "医药"},
    {"symbol": "02313", "name": "申洲国际", "industry": "纺织代工", "sector": "工业"},
    {"symbol": "02318", "name": "中国平安H", "industry": "保险", "sector": "金融"},
    {"symbol": "02319", "name": "蒙牛乳业", "industry": "乳制品", "sector": "消费"},
    {"symbol": "02328", "name": "中国财险", "industry": "保险", "sector": "金融"},
    {"symbol": "02331", "name": "李宁", "industry": "运动服饰", "sector": "消费"},
    {"symbol": "02333", "name": "长城汽车", "industry": "汽车", "sector": "工业"},
    {"symbol": "02380", "name": "中国电力", "industry": "电力", "sector": "公用事业"},
    {"symbol": "02382", "name": "舜宇光学科技", "industry": "光学", "sector": "科技"},
    {"symbol": "02388", "name": "中银香港", "industry": "银行", "sector": "金融"},
    {"symbol": "02600", "name": "中国铝业", "industry": "铝", "sector": "工业"},
    {"symbol": "02601", "name": "中国太保H", "industry": "保险", "sector": "金融"},
    {"symbol": "02628", "name": "中国人寿H", "industry": "保险", "sector": "金融"},
    {"symbol": "02688", "name": "新奥能源", "industry": "燃气", "sector": "公用事业"},
    {"symbol": "02899", "name": "紫金矿业H", "industry": "黄金", "sector": "工业"},
    {"symbol": "03311", "name": "中国建筑国际", "industry": "建筑", "sector": "工业"},
    {"symbol": "03323", "name": "中国建材", "industry": "建材", "sector": "工业"},
    {"symbol": "03328", "name": "交通银行", "industry": "银行", "sector": "金融"},
    {"symbol": "03333", "name": "中国恒大", "industry": "房地产", "sector": "地产"},
    {"symbol": "03692", "name": "翰森制药", "industry": "制药", "sector": "医药"},
    {"symbol": "03888", "name": "金山软件", "industry": "软件", "sector": "科技"},
    {"symbol": "03968", "name": "招商银行H", "industry": "银行", "sector": "金融"},
    {"symbol": "03988", "name": "中国银行H", "industry": "银行", "sector": "金融"},
    {"symbol": "06060", "name": "众安在线", "industry": "互联网保险", "sector": "金融"},
    {"symbol": "06098", "name": "碧桂园服务", "industry": "物业", "sector": "地产"},
    {"symbol": "06160", "name": "百济神州", "industry": "创新药", "sector": "医药"},
    {"symbol": "06185", "name": "康希诺生物", "industry": "疫苗", "sector": "医药"},
    {"symbol": "06186", "name": "中国飞鹤", "industry": "奶粉", "sector": "消费"},
    {"symbol": "06618", "name": "京东健康", "industry": "医疗健康", "sector": "医药"},
    {"symbol": "06690", "name": "海尔智家H", "industry": "家电", "sector": "消费"},
    {"symbol": "06837", "name": "海通证券H", "industry": "证券", "sector": "金融"},
    {"symbol": "06862", "name": "海底捞", "industry": "餐饮", "sector": "消费"},
    {"symbol": "06881", "name": "中信证券H", "industry": "证券", "sector": "金融"},
    {"symbol": "06969", "name": "思摩尔国际", "industry": "电子烟", "sector": "消费"},
    {"symbol": "09626", "name": "哔哩哔哩-SW", "industry": "视频", "sector": "科技"},
    {"symbol": "09633", "name": "农夫山泉", "industry": "饮料", "sector": "消费"},
    {"symbol": "09901", "name": "新东方在线", "industry": "教育", "sector": "消费"},
    {"symbol": "09926", "name": "康方生物", "industry": "创新药", "sector": "医药"},
    {"symbol": "09961", "name": "携程集团-S", "industry": "旅游", "sector": "消费"},
]

# ===== 新增 A 股（不在上面列表中的） =====
EXTRA_A_SHARE = [
    {"symbol": "600690", "name": "海尔智家", "industry": "家电", "sector": "消费"},
    {"symbol": "002460", "name": "赣锋锂业", "industry": "锂", "sector": "新能源"},
    {"symbol": "002466", "name": "天齐锂业", "industry": "锂", "sector": "新能源"},
    {"symbol": "603799", "name": "华友钴业", "industry": "钴", "sector": "新能源"},
    {"symbol": "600309", "name": "万华化学", "industry": "MDI", "sector": "工业"},
    {"symbol": "002271", "name": "东方雨虹", "industry": "防水材料", "sector": "工业"},
    {"symbol": "000786", "name": "北新建材", "industry": "石膏板", "sector": "工业"},
    {"symbol": "600760", "name": "中航沈飞", "industry": "战斗机", "sector": "军工"},
    {"symbol": "601989", "name": "中国重工", "industry": "船舶", "sector": "军工"},
    {"symbol": "002179", "name": "中航光电", "industry": "连接器", "sector": "军工"},
    {"symbol": "600893", "name": "航发动力", "industry": "航空发动机", "sector": "军工"},
    {"symbol": "002414", "name": "高德红外", "industry": "红外", "sector": "军工"},
    {"symbol": "601006", "name": "大秦铁路", "industry": "铁路", "sector": "交运"},
    {"symbol": "600009", "name": "上海机场", "industry": "机场", "sector": "交运"},
    {"symbol": "000089", "name": "深圳机场", "industry": "机场", "sector": "交运"},
    {"symbol": "600029", "name": "南方航空", "industry": "航空", "sector": "交运"},
    {"symbol": "300413", "name": "芒果超媒", "industry": "视频", "sector": "传媒"},
    {"symbol": "002027", "name": "分众传媒", "industry": "广告", "sector": "传媒"},
    {"symbol": "300251", "name": "光线传媒", "industry": "影视", "sector": "传媒"},
    {"symbol": "300070", "name": "碧水源", "industry": "水处理", "sector": "环保"},
    {"symbol": "603568", "name": "伟明环保", "industry": "垃圾焚烧", "sector": "环保"},
    {"symbol": "002714", "name": "牧原股份", "industry": "生猪", "sector": "消费"},
    {"symbol": "300498", "name": "温氏股份", "industry": "生猪", "sector": "消费"},
    {"symbol": "002311", "name": "海大集团", "industry": "饲料", "sector": "消费"},
    {"symbol": "600436", "name": "片仔癀", "industry": "中药", "sector": "医药"},
    {"symbol": "000538", "name": "云南白药", "industry": "中药", "sector": "医药"},
    {"symbol": "600196", "name": "复星医药", "industry": "综合药企", "sector": "医药"},
    {"symbol": "002007", "name": "华兰生物", "industry": "血液制品", "sector": "医药"},
    {"symbol": "300015", "name": "爱尔眼科", "industry": "眼科连锁", "sector": "医药"},
    {"symbol": "300122", "name": "智飞生物", "industry": "疫苗", "sector": "医药"},
    {"symbol": "000661", "name": "长春高新", "industry": "生长激素", "sector": "医药"},
    {"symbol": "300347", "name": "泰格医药", "industry": "CRO", "sector": "医药"},
    {"symbol": "688180", "name": "君实生物", "industry": "创新药", "sector": "医药"},
    {"symbol": "002001", "name": "新和成", "industry": "维生素", "sector": "医药"},
    {"symbol": "600085", "name": "同仁堂", "industry": "中药", "sector": "医药"},
    {"symbol": "300529", "name": "健帆生物", "industry": "血液净化", "sector": "医药"},
    {"symbol": "001979", "name": "招商蛇口", "industry": "房地产", "sector": "地产"},
    {"symbol": "600048", "name": "保利发展", "industry": "房地产", "sector": "地产"},
    {"symbol": "000002", "name": "万科A", "industry": "房地产", "sector": "地产"},
    {"symbol": "600383", "name": "金地集团", "industry": "房地产", "sector": "地产"},
    {"symbol": "600019", "name": "宝钢股份", "industry": "钢铁", "sector": "工业"},
    {"symbol": "601899", "name": "紫金矿业", "industry": "黄金", "sector": "工业"},
    {"symbol": "600104", "name": "上汽集团", "industry": "汽车", "sector": "工业"},
    {"symbol": "000625", "name": "长安汽车", "industry": "汽车", "sector": "工业"},
    {"symbol": "601238", "name": "广汽集团", "industry": "汽车", "sector": "工业"},
    {"symbol": "600741", "name": "华域汽车", "industry": "汽车零部件", "sector": "工业"},
    {"symbol": "002920", "name": "德赛西威", "industry": "智能驾驶", "sector": "工业"},
    {"symbol": "300124", "name": "汇川技术", "industry": "工控", "sector": "工业"},
    {"symbol": "002747", "name": "埃斯顿", "industry": "工业机器人", "sector": "工业"},
    {"symbol": "601669", "name": "中国电建", "industry": "建筑", "sector": "工业"},
    {"symbol": "601668", "name": "中国建筑", "industry": "建筑", "sector": "工业"},
    {"symbol": "601390", "name": "中国中铁", "industry": "基建", "sector": "工业"},
    {"symbol": "601186", "name": "中国铁建", "industry": "基建", "sector": "工业"},
    {"symbol": "601766", "name": "中国中车", "industry": "轨交", "sector": "工业"},
    {"symbol": "600585", "name": "海螺水泥", "industry": "水泥", "sector": "工业"},
    {"symbol": "002230", "name": "科大讯飞", "industry": "AI语音", "sector": "科技"},
    {"symbol": "688111", "name": "金山办公", "industry": "办公软件", "sector": "科技"},
    {"symbol": "300033", "name": "同花顺", "industry": "金融IT", "sector": "科技"},
    {"symbol": "002410", "name": "广联达", "industry": "建筑IT", "sector": "科技"},
    {"symbol": "300496", "name": "中科创达", "industry": "操作系统", "sector": "科技"},
    {"symbol": "688981", "name": "中芯国际", "industry": "晶圆代工", "sector": "科技"},
    {"symbol": "002371", "name": "北方华创", "industry": "半导体设备", "sector": "科技"},
    {"symbol": "688012", "name": "中微公司", "industry": "半导体设备", "sector": "科技"},
    {"symbol": "603501", "name": "韦尔股份", "industry": "芯片设计", "sector": "科技"},
    {"symbol": "300782", "name": "卓胜微", "industry": "射频芯片", "sector": "科技"},
    {"symbol": "688008", "name": "澜起科技", "industry": "内存接口", "sector": "科技"},
    {"symbol": "002049", "name": "紫光国微", "industry": "安全芯片", "sector": "科技"},
    {"symbol": "688036", "name": "传音控股", "industry": "手机", "sector": "科技"},
    {"symbol": "300661", "name": "圣邦股份", "industry": "模拟芯片", "sector": "科技"},
    {"symbol": "688120", "name": "华海清科", "industry": "半导体设备", "sector": "科技"},
    {"symbol": "603290", "name": "斯达半导", "industry": "IGBT", "sector": "科技"},
    {"symbol": "688256", "name": "寒武纪", "industry": "AI芯片", "sector": "科技"},
    {"symbol": "301358", "name": "湖南裕能", "industry": "正极材料", "sector": "新能源"},
    {"symbol": "000063", "name": "中兴通讯", "industry": "通信设备", "sector": "科技"},
    {"symbol": "600941", "name": "中国移动", "industry": "运营商", "sector": "科技"},
    {"symbol": "601728", "name": "中国电信", "industry": "运营商", "sector": "科技"},
    {"symbol": "600050", "name": "中国联通", "industry": "运营商", "sector": "科技"},
    {"symbol": "002475", "name": "立讯精密", "industry": "消费电子", "sector": "科技"},
    {"symbol": "002415", "name": "海康威视", "industry": "安防", "sector": "科技"},
    {"symbol": "002241", "name": "歌尔股份", "industry": "声学", "sector": "科技"},
    {"symbol": "603160", "name": "汇顶科技", "industry": "指纹芯片", "sector": "科技"},
    {"symbol": "300433", "name": "蓝思科技", "industry": "玻璃盖板", "sector": "科技"},
    {"symbol": "002600", "name": "领益智造", "industry": "精密件", "sector": "科技"},
    {"symbol": "688169", "name": "石头科技", "industry": "扫地机器人", "sector": "消费"},
    {"symbol": "300073", "name": "当升科技", "industry": "正极材料", "sector": "新能源"},
    {"symbol": "002129", "name": "TCL中环", "industry": "光伏硅片", "sector": "新能源"},
    {"symbol": "300617", "name": "安靠智电", "industry": "电缆", "sector": "新能源"},
    {"symbol": "600900", "name": "长江电力", "industry": "水电", "sector": "公用事业"},
    {"symbol": "600886", "name": "国投电力", "industry": "水电", "sector": "公用事业"},
    {"symbol": "601985", "name": "中国核电", "industry": "核电", "sector": "公用事业"},
    {"symbol": "600023", "name": "浙能电力", "industry": "火电", "sector": "公用事业"},
    {"symbol": "600011", "name": "华能国际", "industry": "火电", "sector": "公用事业"},
    {"symbol": "003816", "name": "中国广核", "industry": "核电", "sector": "公用事业"},
]

# ===== 新增港股（不在上面列表中的） =====
EXTRA_HK = [
    {"symbol": "00285", "name": "比亚迪电子", "industry": "电子制造", "sector": "科技"},
    {"symbol": "00291", "name": "华润啤酒", "industry": "啤酒", "sector": "消费"},
    {"symbol": "00669", "name": "创科实业", "industry": "电动工具", "sector": "工业"},
    {"symbol": "00823", "name": "领展房产基金", "industry": "REITs", "sector": "地产"},
    {"symbol": "00868", "name": "信义玻璃", "industry": "玻璃", "sector": "工业"},
    {"symbol": "00960", "name": "龙湖集团", "industry": "房地产", "sector": "地产"},
    {"symbol": "00966", "name": "中国太平", "industry": "保险", "sector": "金融"},
    {"symbol": "00992", "name": "联想集团", "industry": "PC", "sector": "科技"},
    {"symbol": "01068", "name": "雨润食品", "industry": "肉制品", "sector": "消费"},
    {"symbol": "01113", "name": "长实集团", "industry": "房地产", "sector": "地产"},
    {"symbol": "01171", "name": "兖矿能源", "industry": "煤炭", "sector": "能源"},
    {"symbol": "01208", "name": "五矿资源", "industry": "矿业", "sector": "工业"},
    {"symbol": "01308", "name": "海丰国际", "industry": "航运", "sector": "交运"},
    {"symbol": "01313", "name": "华润水泥控股", "industry": "水泥", "sector": "工业"},
    {"symbol": "01316", "name": "耐世特汽车", "industry": "汽车零部件", "sector": "工业"},
    {"symbol": "01382", "name": "互太纺织", "industry": "纺织", "sector": "工业"},
    {"symbol": "01448", "name": "福寿园", "industry": "殡葬", "sector": "消费"},
    {"symbol": "01478", "name": "丘钛科技", "industry": "摄像头模组", "sector": "科技"},
    {"symbol": "01691", "name": "JS环球生活", "industry": "小家电", "sector": "消费"},
    {"symbol": "01787", "name": "山东黄金H", "industry": "黄金", "sector": "工业"},
    {"symbol": "01812", "name": "晨鸣纸业H", "industry": "造纸", "sector": "工业"},
    {"symbol": "01818", "name": "招金矿业", "industry": "黄金", "sector": "工业"},
    {"symbol": "01839", "name": "中集车辆", "industry": "车辆", "sector": "工业"},
    {"symbol": "01951", "name": "锦欣生殖", "industry": "医疗服务", "sector": "医药"},
    {"symbol": "01997", "name": "九龙仓置业", "industry": "房地产", "sector": "地产"},
    {"symbol": "02038", "name": "富智康集团", "industry": "电子制造", "sector": "科技"},
    {"symbol": "02068", "name": "中铝国际", "industry": "工程", "sector": "工业"},
    {"symbol": "02099", "name": "中国黄金国际", "industry": "黄金", "sector": "工业"},
    {"symbol": "02120", "name": "康宁医院", "industry": "医院", "sector": "医药"},
    {"symbol": "02208", "name": "金风科技H", "industry": "风电", "sector": "新能源"},
    {"symbol": "02282", "name": "美高梅中国", "industry": "博彩", "sector": "消费"},
    {"symbol": "02357", "name": "中航科工", "industry": "军工", "sector": "军工"},
    {"symbol": "02386", "name": "中石化炼化工程", "industry": "工程", "sector": "工业"},
    {"symbol": "02607", "name": "上海医药H", "industry": "医药流通", "sector": "医药"},
    {"symbol": "02611", "name": "国泰君安H", "industry": "证券", "sector": "金融"},
    {"symbol": "02638", "name": "港灯-SS", "industry": "电力", "sector": "公用事业"},
    {"symbol": "02669", "name": "中海物业", "industry": "物业", "sector": "地产"},
    {"symbol": "02799", "name": "中国华融", "industry": "资产管理", "sector": "金融"},
    {"symbol": "03320", "name": "华润医药", "industry": "医药流通", "sector": "医药"},
    {"symbol": "03331", "name": "维达国际", "industry": "纸品", "sector": "消费"},
    {"symbol": "03360", "name": "远东宏信", "industry": "融资租赁", "sector": "金融"},
    {"symbol": "03383", "name": "雅居乐集团", "industry": "房地产", "sector": "地产"},
    {"symbol": "03759", "name": "康龙化成H", "industry": "CRO", "sector": "医药"},
    {"symbol": "03799", "name": "达利食品", "industry": "食品", "sector": "消费"},
    {"symbol": "03993", "name": "洛阳钼业H", "industry": "矿业", "sector": "工业"},
    {"symbol": "06030", "name": "中信证券", "industry": "证券", "sector": "金融"},
    {"symbol": "06818", "name": "中国光大银行H", "industry": "银行", "sector": "金融"},
    {"symbol": "06865", "name": "福莱特玻璃", "industry": "光伏玻璃", "sector": "新能源"},
    {"symbol": "09909", "name": "宝尊电商", "industry": "电商代运营", "sector": "科技"},
    {"symbol": "09922", "name": "九毛九", "industry": "餐饮", "sector": "消费"},
]


def get_all_stocks() -> list[dict]:
    """返回所有 A 股 + 港股（自动加 market 和 exchange 字段，去重）"""
    seen = set()
    result = []
    for s in A_SHARE_STOCKS + EXTRA_A_SHARE:
        if s["symbol"] in seen:
            continue
        seen.add(s["symbol"])
        exchange = "SH" if s["symbol"].startswith(("6", "5", "9")) else "SZ"
        result.append({**s, "market": "A_SHARE", "exchange": exchange})
    for s in HK_STOCKS + EXTRA_HK:
        if s["symbol"] in seen:
            continue
        seen.add(s["symbol"])
        result.append({**s, "market": "HK", "exchange": "HK"})
    return result


def find_stock_by_symbol(symbol: str) -> dict | None:
    """按代码查找股票"""
    for s in get_all_stocks():
        if s["symbol"] == symbol:
            return s
    return None


def search_stocks_local(keyword: str, market: str = None, limit: int = 20) -> list[dict]:
    """本地模糊搜索（代码或名称）"""
    keyword = keyword.lower()
    results = []
    for s in get_all_stocks():
        if market and s["market"] != market:
            continue
        if keyword in s["symbol"].lower() or keyword in s["name"].lower():
            results.append(s)
            if len(results) >= limit:
                break
    return results
